### ISSUE TITLE
Return info error with steadystate.py and scipy solver

### ISSUE THREAD

**Issue by JetSethi** [qutip/qutip#1017]
We were running the "Steady State Solvers: Optomechanical System" from QuTiP examples, but were repeatedly getting errors. Specifically, line 466 of `steadystate.py` tries to query `max_iter_refine` from `ss_args`, but this line is also executed when using a scipy solver, causing a `KeyError`. 

We were using scipy specifically so that `use_precond` is a valid option.

**Comment by Ericgig** [comment]
Hi the `steadystate` has some problem with optional keyword and scipy/mkl solver.
To have the notebook work, if you have mkl installed, you can change the cell calling `steadystate` to:
```
solvers = ['direct','eigen','power','iterative-gmres','iterative-bicgstab']
mech_dms = []

for ss in solvers:
    if ss in ['iterative-gmres','iterative-bicgstab']:
        rho_ss, info = steadystate(H, c_ops, method=ss, use_precond=True, 
                    use_rcm=True, tol=1e-15, return_info=True)
    else:
        rho_ss, info = steadystate(H, c_ops, method=ss,
                    use_rcm=False, return_info=True)
    print(ss,'solution time =',info['solution_time'])
    rho_mech = ptrace(rho_ss, 1)
    mech_dms.append(rho_mech)
mech_dms = np.asarray(mech_dms)
```
Without mkl installed, skip the 'direct' method.


Help Wanted: Some rework of the keywords_args treatment, testing solver/method mixes ('direct' + 'scipy' should work but don't) updating notebooks and docstring, etc. would be appreciated.

**Comment by tehruhn** [comment]
Hi @Ericgig , could you be a little more specific about what reworking the kwargs treatment would entail? Also if you could emphasize more concretely what you're looking for in updates to the notebooks and docs, that would be great.

I do have some other observations.
1. I do not get the KeyError message if I run the same jupyter notebook locally with the same versions of code as specified by version_table( ). I get another error instead, which actually seems more reasonable to me (something along the lines of 'use_precond' wasn't found in the keys of the dict, which clearly indicates that there's something off with the optional args thing).
2. Also using mech_dms = np.asarray(mech_dms) fails, I think because it sees a Qobj instead of a real number.
3. The direct patch to the KeyError mentioned above, based on my understanding of the code, would simply be to nest the assignment to 'max_iter_refine' in the 'info' dictionary inside a condition that checks if the solver is 'scipy'?

**Comment by Ericgig** [comment]
Hi @tehruhn.
The call to steadystate take different kwargs depending on whether scipy of mkl is solved. It make an error if you give it a keyword not belonging to the right solver. I believe it should be better to accept all keyword and ignore the unused one. If you want to rework it, I would suggest to set the most stable solver/method as a default. I heard the default method sometime fails (#1077). 

2. Since a few version back, when we added a `__array__` method to Qobj. We need to do `np.asarray(mech_dms, dtype=object)`.

**Comment by Ericgig** [comment]
Should be fixed in v5
