### ISSUE TITLE
MacOS header error: fatal error: limits.h: No such file or directory

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip#1030]
MacOS Mojave deliberately deleted the `user/include` folder so when compiling cython code, gcc cannot find the headers. I struggled a bit after suddenly updating to the latest MacOS and could find the solution here:

https://programmer.help/blogs/how-to-resolve-pip-install-twisted-error-limits.h-no-such-file-or-directory.html

Just do 

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

In case others also update and end up with this error. @nathanshammah

**Comment by quantshah** [comment]
Leaving the full error message here:

```
anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
```

**Comment by nathanshammah** [comment]
I also experienced this with the latest 4.4.2(?).dev version.

**Comment by nathanshammah** [comment]
When I try it now, it says that the software plugin is incompatible with the OS, which is 10.14.5, Mojave.

**Comment by nathanshammah** [comment]
gcc is 4.8.5, Xcode 10.2

**Comment by nathanshammah** [comment]
The [workaround](https://stackoverflow.com/questions/58897928/macos-sdk-headers-for-macos-10-14-pkg-is-incompatible-with-this-version-of-maco) for me seems to be 
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
cd /Library/Developer/CommandLineTools/Packages/
open macOS_SDK_headers_for_macOS_10.14.pkg
```

**Comment by Noirad** [comment]
> xcode-select --install


thank you!!!!

**Comment by Noirad** [comment]
> The [workaround](https://stackoverflow.com/questions/58897928/macos-sdk-headers-for-macos-10-14-pkg-is-incompatible-with-this-version-of-maco) for me seems to be
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> cd /Library/Developer/CommandLineTools/Packages/
> open macOS_SDK_headers_for_macOS_10.14.pkg
> ```


thank you!!!!

**Comment by jakelishman** [comment]
For people finding this later, this is not just because of the macOS version, but also because of your _Xcode_ version.  As Xcode increases, Apple are making it harder and harder to have a sensible dev environment for command-line tools when all you care about is building for your local machine.

You may find that a system include like `_ctermid.h` is missing in the future - it won't always be `limits.h` - especially with Xcode 11+.  Since M1 Macs (I assume) ship entirely with Xcode 12, they will likely need this too.

`/usr/include` is gone, but Xcode has the correct set of includes for all platforms, so you can set your compiler's `sysroot` to the relevant SDK directory to get correct lookups.  By default, the one you want will be at
```
/Applications/Xcode.app/Contents/Developer/Platforms/MaxOSX.platform/Developer/SDKs/MacOSX.sdk
```
The system `clang` will likely find this correctly, but if not or if you're using a separate compiler, for either `gcc` or `clang` you should pass the flag
```bash
${cc} -isysroot '/path/to/sdk'
```
to find the correct includes.  To automate this procedure, you may want to add that flag to your `CFLAGS` and `CPPFLAGS` environment variables.  For example, you could put in your `.bashrc`
```bash
export CFLAGS="-isysroot '/path/to/sdk' ${CFLAGS}"
```
to have it automatically added to all C compilations (after that file has been sourced).

**Comment by ilbibi** [comment]
Hello @jakelishman sorry for hopping in, but I'm having the same problem and I'm desperate...

I have xcode 10.3
This is THE error:
```
/usr/local/Cellar/gcc/10.2.0_3/lib/gcc/10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory
  219 | #include <_ctermid.h>
      |          ^~~~~~~~~~~~
```
In the compile flags I see these:

```
-I/usr/local/include 
-F/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

I've tried all suggested above to reinstall all headers, but it's nowhere in my entire disk. 
do you have any ideas?

**Comment by jakelishman** [comment]
I don't know if there was a macOS update or something, but my configuration has gone funny as well.  I find now that using `gcc --sysroot=...` rather than `gcc -isysroot=...` (note the missing `i` and the doubled `--`) works.  I'm not 100% sure why this is the case - as far as I'm aware, the only difference between `--sysroot` and `-isysroot` is just that the latter only applies to includes and the former is both libraries and includes - but it works for me right now.  I must be wrong in some way about the difference.

Hopefully that works for you on a temporary basis.  I'm sure Apple will be along shortly to change everything else up for us again.

**Comment by jakelishman** [comment]
Closing this now because it's not really a QuTiP error, just Apple being Apple.
