### ISSUE TITLE
Correlation functions produce incorrect results with multiple time dependant functions

### ISSUE THREAD

**Issue by taw181** [qutip/qutip#1048]
When using multiple time dependant functions (i.e. H = [H0,[H1,H1_coeff],[H2,H2_coeff],...]) the functions in qutip.correlations produce incorrect results. A couple observations:

- You get different results depending on the order of the time dependant parts. mesolve produces identical results.
- Even if the time-varying Hamiltonian is empty or the function returns zero, it can still affect the results.

I've attached some code demonstrating this (3 level atom and a laser) and some images of the plots produced.
[corrtest.txt](https://github.com/qutip/qutip/files/3398074/corrtest.txt)
[norder2](https://user-images.githubusercontent.com/42548316/61312064-962c0380-a7ef-11e9-84e7-964a5ff49f21.png)
[corrorder2](https://user-images.githubusercontent.com/42548316/61312065-962c0380-a7ef-11e9-8e28-5797fb4004d3.png)
[norder1](https://user-images.githubusercontent.com/42548316/61312066-962c0380-a7ef-11e9-9e5a-dce127d8be11.png)
[corrorder1](https://user-images.githubusercontent.com/42548316/61312067-962c0380-a7ef-11e9-8eb2-532eec7bbb61.png)

I'm assuming this is to do with how the Hamiltonian is propagated, maybe only one of the functions is being shifted in time? Any chance of a fix on this? A workaround is to make the entire Hamiltonian a single time dependant function but obviously this isn't ideal.

**Comment by Ericgig** [comment]
Hi taw181,

Thank you for reporting the bug.
The patch will probably take some time to make and publish. 
A work around for now would be to use string based coefficient. Use `(t)` instead of t in the string, there is another bug in the string shifting code.


-------------------------------------------------------------------------------------------
Self notes

The function _transform_L_t_shift of correlation.py has at least 2 bugs:
- lambda have side-effect when defined in loop:
```
H = [0,1,2]
H_shift = []
for i in range(len(H)):
    fn = lambda _: H[i]
    H_shift.append(fn)
    
for f in H_shift:
    print(f(0))
```
Using class is safer and can be used safely in parallel.

- The shift is not applied properly to string when "t" is the first or last character of the string coefficient.

Could/should this shift capacity be made part of QobjEvo?

**Comment by taw181** [comment]
Brilliant, thanks. I'll try it again with the string method.
