### ISSUE TITLE
minimal required cython version

### ISSUE THREAD

**Issue by daniel-edler** [qutip/qutip#1129]
By installing qutip via

    pip2 install qutip==4.3.1

(I had another problem with qutip 4.4.1 with the python2.7 interpreter) I ran into a problem with cython - several "Error compiling Cython file" messages. Here I have cython v. 0.23.4 and the minimum requirement is displayed as 0.21. I guess this minimum requirement should be changed

**Comment by nathanshammah** [comment]
python 2 is not any more supported by QuTiP. Try with Python 3.

**Comment by jakelishman** [comment]
This is old, but caught my eye - it might be worth us revisiting.  There's a few places in the code where the version requirement is 0.14, and also I'm not 100% certain that 0.21 is the minimum requirement anymore; I think the ability to pickle `cdef`'ed classes requires 0.26.  Perhaps @Ericgig knows?  The `cython >= 0.21` requirement was added in 836ab63 back in December 2016.

Also, `cython` isn't actually a hard requirement, just like `matplotlib` (which was removed from `requirements.txt` in bc7b3c0 (February 2014) because they weren't mandatory.  Maybe something to add in to the [testing and distribution project](https://github.com/qutip/qutip/projects/3)?

**Comment by Ericgig** [comment]
We removed the need for cython at run time (officially) recently. It is still needed at installation for installation from sources, but conda can be used if cython is not available. I am not sure about the minimum version, but it does not have to be that recent. Pickling of cdef class is done manually and depend more on pickle version than cython's.
We don't support python2 anymore since numpy also removed it's support, but 4.3 or 4.2 should date from a time it was still supported.

Are some of the cython files compiling or are they all failing?

**Comment by jakelishman** [comment]
Closing this for now as the runtime optional requirement has been updated to 0.29.20 as of #1465.
