### ISSUE TITLE
Value of hbar 

### ISSUE THREAD

**Issue by nquesada** [qutip/qutip#1148]
It might be helpful to say somewhere visible in the documentation what is the value of hbar in the canonical commutation relation [x,p] = i hbar that is used by qutip.

I understand that this is implicit in the value taken for `g` in the `wigner` module, but it would be nice making it easier for the user.
Also, note that in the function `wigner_covariance_matrix` you assume hbar = 1. It would be good to either make this explicit or allow an optional `g` argument to be passed.

Thanks for your work in this great library!

**Comment by nathanshammah** [comment]
Thank you for spotting this. Could you help fix it? This would be a https://github.com/qutip/qutip-doc pull request.

**Comment by nquesada** [comment]
Cool. I am more than happy to fix it, but would like to know where should I add this...

**Comment by nathanshammah** [comment]
You can make two pull requests: 
1. You could add this information in the docstring of the `wigner` functions here in `qutip/qutip`, 
so that it appears here http://qutip.org/docs/latest/modules/qutip/wigner.html
2. PR to to [`qutip/qutip-doc`]( https://github.com/qutip/qutip-doc) http://qutip.org/docs/latest/guide/guide-visualization.html#quasi-probability-distributions
by modifying the file `guide/guide-visualization.rst`

**Comment by nathanshammah** [comment]
@nquesada just pinging you as it would be great to have your contribution in the upcoming version release in a week or so.

**Comment by nquesada** [comment]
Sorry for the delay @nathanshammah . I have made the changes in https://github.com/qutip/qutip/pull/1165 .

Looking forward to see the new release!
