### ISSUE TITLE
qutip.testing.run() NameErrors

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1158]
I think there's been some form of merge conflict in `qutip.testing` - for one, it looks like the tests are intended to run twice (once under `pytest` and once under `nose`), and secondly it refers to the name `qset`, which isn't defined.

**Comment by nathanshammah** [comment]
I think you are right. According to [this version](https://github.com/qutip/qutip/commit/0d23a5b72e3eb2c9567d8a3918388cf96370438a#diff-b979016620c6998841cf7cefe791ebfe) and [this one](https://github.com/qutip/qutip/commit/97a65a3fee0983ae2d823a4fdf886aa02965ee5b#diff-b979016620c6998841cf7cefe791ebfe), before some of the latest and recent commits, the changes should be 
- `import qutip.settings as qset` 
- set the settings properties before running the tests
- delete the `nose` tests.
 
Would you like to fix it?

**Comment by jakelishman** [comment]
I've sent a PR #1161 that fixes this, but a bigger worry is why this wasn't caught on Travis on other commits?  I'm not familiar with the CI system, but at a cursory glance it looks like it just tests that QuTiP builds, and not that the tests succeed.  Is that intentional?

**Comment by nathanshammah** [comment]
I think that `qutip.testing` and the tests in CI are different. The former are in that file, the latter look at the instructions from [`.travis.yml`](https://github.com/qutip/qutip/blob/master/.travis.yml), which basically call `python setup.py install` (or `test`). Also looking at the Travis CI reports, it seems that they work fine. Locally, I'm getting tests to fail on my machine, with malloc or abort trap 6 errors every other time, although some time they pass (hence I opened #1160). It may be that they fail on my machine due to some mess with the gcc compiler.

**Comment by jakelishman** [comment]
Yeah, that was what I was referring to - Travis just tests that the Cython parts compile.  I'm new to working on code in any kind of organisation, so I wasn't sure if it's normal to have the unit tests run as part of the CI process, or if that was only meant to test the installation path.
