### ISSUE TITLE
Issue with Creating Coherent States

### ISSUE THREAD

**Issue by alipedram01** [qutip/qutip#1162]
The function "coherent" gives different results for analytic and operator methods. For example, for the two dimensional Hilbert space and with eigenvalue of the coherent state equal to one the analytic method is as follows,
coherent(2, 1, offset=0, method='analytic') which results in,
(0.607, 0.607)'
which is the correct column vector, but not normalized. However for the operator method,
coherent(2, 1, offset=0, method='operator') the result is,
(0.540, 0.841)'
which is wrong.

**Comment by nonhermitian** [comment]
Analytic is the results for an infinite Hilbert space. Operator method computes the proper operator in the truncated Hilbert space. Always use the operator one in practice.

**Comment by nathanshammah** [comment]
As the docstring says, `coherent()` 
```
Generates a coherent state with eigenvalue alpha.
Constructed using displacement operator on vacuum state.
```
It should not be normalized. In the `operator` method, the problem is that you are imposing a very low cut-off for the Hilbert space. In theory, the "correct" value is for $N=\infty$. Here you are imposing `N=2`. This is a very bad approximation of a bosonic state.  

I think it is best to continue the conversation on QuTiP google's forum, if you still have doubts. https://groups.google.com/forum/#!forum/qutip
