### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by PiggsBoson** [qutip/qutip#1180]
I'm using qutip to simulate lindblad dynamics. However, compared to the method I wrote myself with scipy, the one I wrote with qutip mesolve() was much slower. Did I do something wrong or it's expected?
Here's my code

```python
def simulate_lind (self, t):
		"""simulate the lindblad dynamics
		Arguments:
			t -- time for propagation
		"""
		if self.impl == 'direct':#my implementation
			rho0 = np.reshape(self.psi0, (self.n)**2)
			r = ode(self.__lind).set_integrator('zvode', method='bdf')
			r.set_initial_value(rho0, 0)
			r.set_f_params(self.H, self.gamma,  self.A, self.n)
			r.integrate(r.t)
			rhot = r.y
			rhot = np.reshape(rhot, (self.n, self.n))
		elif self.impl == 'qutip': #with qutip
			rho0 = Qobj(self.psi0)
			rhot = mesolve(Qobj(self.H), rho0, [0, t], [np.sqrt(self.gamma) * Qobj(self.A)]).states[-1].full()
		self.psi0 = rhot
		return self.psi0
```

**Comment by Ericgig** [comment]
The core of `mesolve` is also `scipy.ode`, but the default method is `adams` instead of `bdf` and we use sparse matrix for the liouvillian.

There are a lot of small time lost with using mesolve like this. Just looking at rhos' datatype: 
`self.psi0: dense -> rho0: Qobj(sparse matrix) -> dense vector (for ode) -> mesolve return: sparse matrix -> rhot: dense...`
Also `mesolve` will check if the Hamiltonian is really an Hamitonian or a Liouvillian or a function returning an Hamiltonian, if the system depend on time, if all the dimensions match, etc. So the overhead of `mesolve` will be important.

Finally, depending on the Hamiltonian there can be a good difference in speed. We use sparse matrix for the Liouvillian, good if the Hamiltonian is large with few non-zeros, but slower that simple dense matrices otherwise.

**Comment by TejasAvinashShetty** [comment]
Same here

**Comment by CaineArdayfio** [comment]
Hello, I'm new to GitHub contributing and was wondering if there was still an issue to be solved here. I'm happy to help.

**Comment by jakelishman** [comment]
Closing because I'm not sure there's a problem to be fixed here.  At any rate, dense matrices will get huge speed improvements in QuTiP 5.0.
