### ISSUE TITLE
Cannot find qcirc.svg

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1185]
In QuTiP 4.5.0 conda release on Mac, I get an error if I call a quantum circuit to print in jupyter notebook. However, the circuit is printed after the message. 

This did not happen with QuTiP 4.4.1. Imagemagick is installed. This issue may be related to the closed issues #1179 and #702.

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/miniconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/miniconda3/lib/python3.7/site-packages/qutip/qip/circuit.py in _repr_svg_(self)
   1117 
   1118     def _repr_svg_(self):
-> 1119         return _latex_compile(self.latex_code(), format="svg")
   1120 
   1121     @property

/miniconda3/lib/python3.7/site-packages/qutip/qip/circuit_latex.py in _latex_compile(code, filename, format)
     64     else:
     65         os.system("pdf2svg %s.pdf %s.svg" % (filename, filename))
---> 66         with open("%s.svg" % filename) as f:
     67             result = f.read()
     68 

FileNotFoundError: [Errno 2] No such file or directory: 'qcirc.svg'
```
<img width="1137" alt="Screenshot 2020-02-26 17 44 05" src="https://user-images.githubusercontent.com/14573436/75327357-9af58180-58bf-11ea-9989-6892f5b7af41.png">

**Comment by jakelishman** [comment]
`pdf2svg` isn't part of ImageMagick, (at least on `brew`) is http://www.cityinthesky.co.uk/opensource/pdf2svg.  It feels like all of these system commands should be made a bit more robust.

In particular, the bare `os.system` is not the recommended way of calling out to system commands any more.  It's now preferable to use [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run).  Here, the bug is, I would assume, actually on the previous line:
```python
os.system('command_which_does_not_exist')
```
will return a non-zero error code which isn't checked for, but will not raise an exception.  

If Jupyter supports displaying embedded PDF files and that's all it's being used for, then it might be worth removing the conversion to SVG.  (pdf)LaTeX certainly supports embedded PDF files as graphics.  The fewer little dependencies we require, the better.

**Comment by jakelishman** [comment]
Also, while this is neither here nor there, #1179 isn't yet closed, merged, or ready for merge.

**Comment by christian512** [comment]
I've had the same problem recently, trying to plot some circuits. Had to dig into the code to find which packages were missing. Maybe we could replace the `os.system()` calls with a the `subprocess.run()` and show on which call the code failed.

**Comment by sarsid** [comment]
Just a small comment in the meanwhile, might be instructive to run the code on ipython (on the terminal instead of jupyter), usually it gives the behavior of os.run() commands as well. Might help with installation of missing packages.
