### ISSUE TITLE
Faster automated test

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1217]
Travis only runs 5 test suite in parallel. Each tested commit have 6 to 8 test suite (add 3.8 and 3.8 for mac) and each test take 20 to 30min. So if many of us are working at the same time, automated test can take a few hours to run (like today).
I propose:
1) Run the short suite for older python version (3.6 and 3.7), keeping the full test for only the latest for each os (linux + mac).
2) For the specialised test (mkl, openmp, no cython) only run test affected by it.

While this will probably not speed up for when only one PR is done, it should help when many are lined up.

(2) could be done by adding new marks for the tests. @jakelishman, will this cause conflict with your unmerged PRs.

**Comment by jakelishman** [comment]
For point 2: adding marks right now will cause conflicts, but if #1181 gets merged then it'll be much simpler.  The main issue is that a lot of the testing structure has changed for tests up to `test_mcsolve.py` alphabetically, and so in general the tests are just not the same.

The principle is pretty straightforwards - just like #1181 introduces a `requires_cython` mark, we would add `uses_cython`, `uses_mkl` and `uses_openmp` marks.  These would be even simpler to add than `requires_cython` because unlike it, they don't require any test-generation logic at all.

The change would simply be to add them to `pytest.ini`, mark the requisite functions and then change the pytest invocation of the specialised test to `pytest -m "uses_cython"` or whatever.  As far as I'm aware, the only parts of their codebase which modify their behaviour based on whether `Cython` is available is `QobjEvo`.  The other parts (like `brmesolve`) just don't work if Cython isn't there.

The MKL tests would become very short; by my reckoning, MKL is only used by `steadystate` and `countstat`.  OpenMP is much more pervasive, as `sesolve`, `mesolve` and `brmesolve` all use it, and parts which depend on those are generally the slowest tests.

The short tests could just become `pytest -m "not slow"`?  That's not super speedy, but it takes about half the time, maybe.  If you want more, then a good starting point is `pytest --durations=0` which will tell us which tests are the slowest (perhaps that was what you already did when marking the slow ones?).

**Comment by Ericgig** [comment]
I am hoping to save more time with "not slow", I am hoping for about a 3~4x faster. Maybe I will remove 3.6 to save more time. Other test that need mark will wait for #1181 for now.

**Comment by jakelishman** [comment]
So I ran the tests with `pytest -m "not slow"` (on my current #1181 branch) with profiling on, so I've got the following additional slow tests that we could mark to cut down the total time.  Here are the tests that took longer than 1 second:
```
35.75s call     test_stochastic_me.py::test_ssesolve_feedback
33.73s call     test_stochastic_se.py::test_ssesolve_feedback
25.80s call     test_sesolve.py::TestSESolve::test_06_4_compare_state_and_unitary_list_str
24.41s call     test_correlation.py::TestTimeDependence::test_varying_coefficient_hamiltonian_2ls[string]
21.83s call     test_propagator.py::testPropHOStrTd
19.95s call     test_mesolve.py::TestMESolveSuperInit::testMETDDecayAsStrList
17.73s call     test_qobjevo.py::test_QobjEvo_expect_rho
16.52s call     test_stochastic_me.py::test_smesolve_homodyne
15.79s call     test_qobjevo.py::test_QobjEvo_call
12.67s call     test_correlation.py::TestTimeDependence::test_varying_coefficient_hamiltonian_2ls[numpy]
12.37s call     test_mesolve.py::TestMESolveStepFuncCoeff::test_array_str_coeff
11.43s call     test_qobjevo.py::test_QobjEvo_mul_mat
10.89s call     test_spmath.py::test_csr_kron
10.83s call     test_qobjevo.py::test_QobjEvo_expect_psi
9.89s call     test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[QFT-Qobj propagation]
9.40s call     test_mesolve.py::TestMESolverConstDecay::testMEDecayAsStrList
9.32s call     test_sesolve.py::TestSESolve::test_04_2_unitary_with_list_func_H
8.74s call     test_brmesolve_td.py::test_split_operators_maintain_answer[_2_tuple_split]
8.38s call     test_qobjevo.py::test_QobjEvo_call_args
8.37s call     test_mesolve.py::TestMESolveTDDecay::testMETDDecayAsStrList
8.34s call     test_qobjevo.py::test_QobjEvo_pickle
8.21s call     test_qobjevo.py::test_QobjEvo_safepickle
8.11s call     test_qobjevo.py::test_QobjEvo_with_state
7.79s call     test_scattering.py::TestScattering::testScatteringProbability
7.69s call     test_brtools.py::test_diag_liou_mult
7.48s call     test_qobjevo.py::test_QobjEvo_mul_vec
6.89s call     test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Symplectic coupled oscillators-Qobj propagation]
6.04s call     test_qubit_evolution.py::test_MCSolverCase1
5.90s call     test_brmesolve_td.py::test_time_dependent_spline_in_c_ops
5.71s call     test_control_pulseoptim.py::TestFileIO::test_dumping_to_files
5.67s call     test_sesolve.py::TestSESolve::test_04_1_state_with_list_str_H
5.36s call     test_mesolve.py::TestMESolveSuperInit::testSuperJC
5.23s call     test_parallel.py::test_serial_map
5.11s call     test_sesolve.py::TestSESolve::test_06_2_compare_state_and_unitary_func
5.05s call     test_partial_transpose.py::test_partial_transpose_comparison
5.05s call     test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Ising state-to-state-Qobj propagation]
5.01s call     test_qobj.py::test_dual_channel[sub_dimensions3]
4.84s call     test_mesolve.py::TestMESolveSuperInit::testMETDDecayAsArray
4.79s call     test_parallel.py::test_parallel_map
4.27s call     test_spinchain.py::TestSpinChain::test_analytical_evo
3.92s call     test_stochastic_se.py::test_ssesolve_homodyne
3.86s call     test_correlation.py::TestTimeDependence::test_hamiltonian_from_function_2ls
3.25s call     test_mesolve.py::TestMESolveSuperInit::testMETDDecayAsPartFuncList
3.23s call     test_control_pulseoptim.py::TestOptimization::test_unitarity_via_dump
3.03s call     test_control_pulseoptim.py::TestOptimization::test_basic_optimization[QFT-Qobj propagation]
2.65s call     test_control_pulseoptim.py::TestOptimization::test_crab[Qobj propagation]
2.57s call     test_wigner.py::test_wigner_compare_methods_dm
2.46s call     test_control_pulseoptim.py::TestOptimization::test_basic_optimization[Symplectic coupled oscillators-Qobj propagation]
2.31s call     test_parallel.py::test_parfor1
2.11s call     test_wigner.py::test_wigner_bell1_su2parity
1.90s call     test_control_pulseoptim.py::TestOptimization::test_basic_optimization[Ising state-to-state-Qobj propagation]
1.86s call     test_sparse.py::test_sp_profile
1.66s call     test_correlation.py::test_correlation_solver_equivalence[es-legacy]
1.65s call     test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Lindbladian amplitude damping channel-Qobj propagation]
1.56s call     test_correlation.py::test_correlation_solver_equivalence[es]
1.43s call     test_mesolve.py::TestMESolveStepFuncCoeff::test_array_str_py_coeff
1.43s call     test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Symplectic coupled oscillators-default propagation]
1.40s call     test_correlation.py::test_correlation_solver_equivalence[es-steady state]
1.38s call     test_correlation.py::test_correlation_solver_equivalence[es-steady state-legacy]
1.32s call     test_mesolve.py::TestMESolveSuperInit::testMETDDecayAsFunc
1.17s call     test_optpulseprocessor.py::TestOptPulseProcessor::test_multi_gates
1.13s call     test_utilities.py::test_unit_clebsch
1.08s call     test_brtools.py::test_vec_to_eigbasis
1.03s call     test_brtools.py::test_eigvec_to_fockbasis
1.02s call     test_subsys_apply.py::TestSubsysApply::test_ComplexSingleApply
```

**Comment by Ericgig** [comment]
We need to be careful not to remove too much, we need keep the tests meaningful, with a good coverage. 
The first 2 are quite rare cases and could be marked as slow. Or at least one of them since they are quite similar.
Tests in QobjEvo could be rearranged to limit the number of compilations.

**Comment by jakelishman** [comment]
Yeah, definitely there's no point running tests that aren't really testing the package properly.

I would hope that if we're much more aggressive about converting time-dependent lists into QobjEvo objects inside `mesolve`, `mcsolve` and `sesolve` (or the class-based versions of them), we could significantly reduce the amount of testing that needs to be done with them.  Most of the tests of time-dependent formats would then occur in the QobjEvo tests.

We could still test all the configurations of the solvers without too heavy a time penalty.  If we only use a small number of different time-dependent operators, we can compile them all only once, and have `pytest` manage the resources through shared fixtures.  That would really cut down the run times, especially for the current "slow" tests.

Another avenue for cutting down run time is if we could merge say the MKL and OpenMP tests into one Travis job - the setup time for one job is about 2.5 minutes, and that's before any tests have run at all.  I would hazard a guess that having MKL but not OpenMP is a pretty rare case (maybe more common on high-performance clusters where people submit single-cpu jobs?).

**Comment by jakelishman** [comment]
Our tests could still be shortened, but right now the `pytest.mark.slow` marker does allow for a reasonable run time without sacrificing too much, and we have reduced our Travis load to only 5 concurrent tests by merging MKL and OpenMP tests.  With `Coefficient` on `dev.major` we have a lot more scope for re-using compiled coefficients, which are typically the slow parts, but for now I think our testing is much faster than it was when this issue was first opened.
