### ISSUE TITLE
Python Headers

### ISSUE THREAD

**Issue by hljlichao** [qutip/qutip#1222]
Is Python Headers a package? How to install? It is required for the following reason.
Python Headers 2.7+ Linux only. Needed for compiling Cython files
http://qutip.org/docs/latest/installation.html
Thanks~

**Comment by hljlichao** [comment]
I carefully followed the instruction and installed qutip on a ubuntu system in windows. It seems the the only package I did not explicitly installed is Python Headers.
After installing qutip and running the test, I got the following:
634 passed, 6 skipped, 61 deselected, 2 xfailed, 959 warnings in 236.31s (0:03:56)
qutip/tests/test_metrics.py::test_unitarity_known XFAIL                                                                                           [ 35%]
qutip/tests/test_metrics.py::test_unitarity_bounded XFAIL                                                                                         [ 35%]
qutip/tests/test_metrics.py::test_dnorm_bounded SKIPPED                                                                                           [ 35%]
qutip/tests/test_metrics.py::test_dnorm_qubit_known_cases SKIPPED                                                                                 [ 35%]
qutip/tests/test_metrics.py::test_dnorm_qubit_scalar SKIPPED                                                                                      [ 36%]
qutip/tests/test_metrics.py::test_dnorm_qubit_triangle SKIPPED                                                                                    [ 36%]
qutip/tests/test_metrics.py::test_dnorm_force_solve SKIPPED                                                                                       [ 36%]
qutip/tests/test_metrics.py::test_dnorm_cptp SKIPPED                                                                                              [ 36%]

I am wondering how to solve these problems.  
As a beginning, I feel it is really challenging to install the package and being free of errors.

**Comment by jakelishman** [comment]
1. Don't worry, those aren't problems.  A problem would just say "FAIL".  "XFAIL" means "expected to fail", which in this case is because those tests were written for an older testing framework and haven't been updated yet.
2. No, you don't need to worry.  If it's installed, you'll get a message at the end which says something like
```====== 1000 passed, 50 skipped, 10 xfailed in 120s ======```
where the numbers and times will be different, but there won't be any red text saying "10 failed" ("xfailed" is fine).

If you've installed `qutip` from `conda` following the [recommended instructions here](http://qutip.org/docs/latest/installation.html#platform-independent-installation), then you should have a valid installation without any issues, and Cython should have sorted itself out.  The general principle is that installing `qutip` is as easy as running
```conda install qutip```
if you've got the `conda-forge` channel activated.
