### ISSUE TITLE
Develop package on Mac 

### ISSUE THREAD

**Issue by Eeonum** [qutip/qutip#1230]
I am installing on Mac OS Catalina using the following command:

python setup.py develop --with-openmp

However, I am getting the following error:

clang: error: unsupported option '-fopenmp'
error: command 'g++' failed with exit status 1

could you please elaborate?

**Comment by nathanshammah** [comment]
It looks like a compiler (g++, gcc)-related issue with your environment. It doesn’t look like a bug of QuTiP.

**Comment by jakelishman** [comment]
The default Apple `clang` version doesn't recognise `-fopenmp` out-of-the-box, because Apple don't ship an OMP library with macOS.  You'll have more luck (with most C/C++ projects!) if you install a fully-featured compiler and environment.  On [homebrew](https://brew.sh) you can find both `clang`/`clang++` and `gcc`/`g++`, both of which can be installed with OMP support.  Make sure your set `PATH`/`CC`/`CXX` environment variables are set up correctly after you've installed, so you're calling the compiler you've just installed, not just the Xcode versions.

This isn't a bug in QuTiP, although we could remember this when somebody's working on modernising the distribution - in C/C++ land, tools like `automake` run through a big list of things to check during build configuration, and one of them is if OMP appears to exist.
