### ISSUE TITLE
Spin-phonon coupling.

### ISSUE THREAD

**Issue by sajidali875** [qutip/qutip#1235]
**Describe the issue**
Hello Everyone, 
I was wondering if someone could lead me to an example, a tutorial or a code in which single spin coupled with lattice vibration is modelled. I will really appreciate any help in this regard.

**To Reproduce**

```python
from qutip import identity
print(identity(2))
```
The terminal out put is
```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
```

**Comment by nathanshammah** [comment]
You can find several examples in qutip.org tutorials page. 
The `jmat` operator allows to define [spins](http://qutip.org/docs/latest/apidoc/functions.html#qutip.operators.jmat). 
This sort of questions are better suited for the [forum](https://groups.google.com/forum/#!forum/qutip), so I'm closing the issue here.
