### ISSUE TITLE
Update setup to development requirements

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1263]
**Issue**
Currently, to develop qutip from source (e.g., installing from)the installation guide says to do 
```
python setup.py develop
```
However, it is [suggested](https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop) to use the command
```
pip -e .[development]
```
This currently is not supported as there is no `development_requirements.txt` file. Also, in dev mode, one needs to install pytest, otherwise the `qt.run()` fails. If pytest as well as cython numpy and scipy were specified in such file, this should be done automatically.  

Additionally, it may be ideal to pin only minor versions with tilde, stuff like  `numpy~=1.18.1`, which should update micro releases but not minor. 

**Describe the solution you'd like**
Add a `development_requirements.txt` file and in setup add
```
extras_require={
        'development': set(dev_requirements),
        'test': dev_requirements,
```
the set option should be needed for how pypi wants it given. 

Add tildes pinning.

**Comment by jakelishman** [comment]
This PR is mostly obseleted by the merging of #1465, since the complete build structure is now different.  In that we didn't necessarily implement the complete change requested here (we don't have `pytest` as a requirement), but we do have the PEP-517-approved way of fully specifying build requirements, so getting a correct build environment is automated.

I will note that `pip install -e .` doesn't play very nicely with packages with Cython components to build; at the time of writing, `pip` would tend to install dependencies and perform the build in a venv regardless of what was installed in the activated Python environment (especially if conda), which meant that the complete set of Cython files needed to be re-compiled every time this command was run.  That's fine if you just want to edit the Python files, but `setup.py develop` would correctly remember which Cython files actually _needed_ to be re-compiled, so remains much more useful for low-level QuTiP development for practical purposes right now.
