### ISSUE TITLE
Issue with bumpy array

### ISSUE THREAD

**Issue by life-elixir** [qutip/qutip#1272]
**Describe the bug**
I'm trying to run some example projects but consistently run into an issue with numpy. I'm quite new to numpy so I couldn't figure out a suitable fix.

The following is taken from J. R. Johansson's tutorial 1 (Jaynes Cumming Model), which ran on numpy 1.81. I am currently running numpy 1.16.5. I also tested lower versions of numpy down to 1.14.0
**To Reproduce**
Here is the code to reproduce it:

```python
output = mesolve(H, psi0, tlist, c_ops, [])

# find the indices of the density matrices for the times we are interested in
t_idx = where([tlist == t for t in [0.0, 5.0, 15.0, 25.0]])[1]
tlist[t_idx]

rho_list = array(output.states)[t_idx]
```
The terminal out put is
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-f8edfb054c33> in <module>
      1 # get a list density matrices
----> 2 rho_list = array(output.states)[t_idx]

TypeError: must be real number, not Qobj
```

**Comment by BoxiLi** [comment]
Hi @life-elixir, you cannot convert `output.states` to a NumPy array because it is a list of class object defined in QuTiP (called `Qobj`). It is not just a matrix but has other attributes like dimensions. If you want to select a state from `output.states` at a certain time step `t`, you can use its index in your `tlist`.

For example:
You have ``tlist = np.array([0, 0.1, 0.2, 0.3])``.
To get the state at `t = 0.2`, use ``output.states[2]``.
