### ISSUE TITLE
Add a __hash__ method for qutip.Qobj

### ISSUE THREAD

**Issue by MichalKononenko** [qutip/qutip#1321]
**Is your feature request related to a problem? Please describe.**
I would like to use a [``qutip.Qobj``](http://qutip.org/docs/latest/apidoc/classes.html#qobj) as a key for a [``functools.lru_cache``](https://docs.python.org/3/library/functools.html#functools.lru_cache), but since the [``qutip.Qobj``](http://qutip.org/docs/latest/apidoc/classes.html#qobj) is not hashable, I can't do this.

**Describe the solution you'd like**

I can implement ``qutip.Qobj.__hash__``, which would hash the dims and the data of the ``qutip.Qobj``.

**Describe alternatives you've considered**

**Additional context**

**Comment by jakelishman** [comment]
We can't implement `__hash__` for `Qobj`, sorry - it's just not possible while following the [Python data model](https://docs.python.org/3/reference/datamodel.html#object.__hash__).  The two principle points that a hash function must follow from there are
1. objects which compare equal with `__eq__` have the same hash
2. the hash of an object cannot change after instantiation (no mutable types)

Unfortunately we fail on both points.  `Qobj.__eq__` is a rounding match, because it gives a total `True` or `False` based on a floating point tolerance, not on exact equality.  I'm not aware of any hash function which can handle this.  Second, the `data` attribute of a `Qobj` is mutable in-place, and so hashing based on the data in the object is not valid.  This is the same reason that `list` and `np.ndarray` are also not hashable types.

If your cache is just for memoisation over a small number of `Qobj` where you know that floating-point tolerance will never be an issue, you may be able to get away with rolling your own cache decorator which uses linear lookup rather than constant-time.  I mean something like
```python
In [1]: import functools
   ...: import qutip
   ...:
   ...: def linear_cache(f):
   ...:     cache = []
   ...:     @functools.wraps(f)
   ...:     def out(*args):
   ...:         for cached_args, cached_value in cache:
   ...:             if args == cached_args:
   ...:                 print("Getting from cache")
   ...:                 return cached_value
   ...:         print("Computing new value")
   ...:         value = f(*args)
   ...:         cache.append((args, value))
   ...:         return value
   ...:     return out
   ...:
   ...: @linear_cache
   ...: def negate(x):
   ...:     return -x
   ...:
   ...: sx = qutip.sigmax()
   ...: sy = qutip.sigmay()
   ...: negate(sx)
   ...: negate(sx)
   ...: negate(sy)
   ...: negate(sx)
   ...: negate(sy)
Computing new value
Getting from cache
Computing new value
Getting from cache
Getting from cache
```
Obviously this will clearly lead to degraded performance if you need to do it for a large number of possible inputs, but if you have a relatively small number of inputs and your cached function is computationally expensive, this may be a way to achieve what you want.

**Comment by sarsid** [comment]
Apropos of nothing else, I think this might be worth a look:
https://github.com/pixelogik/NearPy

**Comment by MichalKononenko** [comment]
Thank you so much for the follow-up. I'll use the decorator.
