### ISSUE TITLE
Can the initial state for mcsolve be a mixed state?

### ISSUE THREAD

**Issue by PaulisBeetle** [qutip/qutip#1375]
If I try to calculate the time evolution of a mixed state by `mcsolve`,  `mcsolve` will raise an error: `initial state must be a state vector`. It seems that we cannot define a single quantum trajectory for a mixed state from a physics perspective. But it is still possible that we can replace H|psi> and c|psi> with -i* [H,rho] and c * rho * c^\dagger respectively to simulate. I am not sure it is a faster way compared to `mesolve`. Can I do a Monte Carlo evolution for a mixed state in QuTip? Thanks.

**Comment by Ericgig** [comment]
`mcsolve` can only evolve ket states. The closest to what you want is `photocurrent_mesolve` which does master equation evolution of a density matrix with the liouvillian build from `H` and `c_ops` but using discrete jumps for `sc_ops`. It is a lot slower than mesolve since it use only basic ode method (Euler's or Heun's method) and you need to set a very small time step to keep the error resonable.

**Comment by PaulisBeetle** [comment]
Thanks for your reply.
