### ISSUE TITLE
Fidelity is coming as 1 for maximally mixed two qubit state

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [qutip/qutip#1423]
**Describe the bug**
I am trying to find the fidelity of the maximally mixed two qubit state. I got fidelity as one where it should be zero. I am attaching the file and the results.

**To Reproduce**
I created a maximally mixed state as 1/2*|00> + 1/2*|01> + 1/2*|10> + 1/2*|11> . I want to check the relation between Concurrence and Fidelity. Concurrence is working correctly, but in case of Fidelity I am facing the issue. I calculated Fidelity using partial trace. Partial traces are giving the same results for both basis (0 and 1) and hence Fidelity is coming as one.

```python
def two_qubit_mixed_state(a, b, c):
    
    if (a >= 0 and b >= 0 and c >= 0) and (a*a + b*b + c*c <= 1):
        d = math.sqrt(1 - (a*a + b*b + c*c))
        
        if d >= 0:
            i = tensor(basis(2, 0), basis(2, 0))
            j = tensor(basis(2, 0), basis(2, 1))
            k = tensor(basis(2, 1), basis(2, 0))
            l = tensor(basis(2, 1), basis(2, 1))
            
            obj = a*i + b*j + c*k + d*l
            pa = obj.ptrace(0)
            pb = obj.ptrace(1)
            qstate1 = (ket2dm(obj))
            
            concurrence_measure = concurrence(qstate1)
            
            fidelity_m = fidelity(pa, pb)
            
            print(qstate1)
            print(pa)
            print(pb)
            print(concurrence_measure)
            print(fidelity_m)
    return obj
            
two_qubit_mixed_state(1/2, 1/2, 1/2)

**Comment by jakelishman** [comment]
Partially tracing either system out of a maximally mixed state _should_ be the same (and is, in QuTiP), so the fidelity being 1 is correct from a matrix view.  QuTiP doesn't track what systems used to exist before a partial trace, so a partial trace from 2 qubits to 1 qubit appears to live in the same Hilbert space no matter which qubit is traced out.  This is the expected behaviour - it's generally the most convenient, rather than doing something odd like giving back the remaining systems tensored with a maximally mixed state on the parts we just traced out.

I'm not sure of the relation between quantum state fidelity and concurrence that you're referring to, so I can't really comment on that.

By the way, your code doesn't actually use a maximally mixed state, but the result is the same anyway. Being able to write (|00> + |01> + |10> + |11>)/2 in ket form like that shows it's pure over the basis you've defined.  The maximally mixed state over this complete basis would be (|00><00| + |01><01| + |10><10| + |11><11|)/4, which isn't the same as the projector onto your state (which also has crossterms like |00><11| and so on).
