### ISSUE TITLE
Quantum discord with python

### ISSUE THREAD

**Issue by mba5811** [qutip/qutip#1450]
Dear all,

Does anybody have a code in python to calculate quantum discord for general two-qubit states?
Many thanks

**Comment by BoxiLi** [comment]
The function `entropy_vn` to compute entropy seems to be what you are looking for.

For specific physics problem, it is better to use the google group: https://groups.google.com/g/qutip. There are more users active there. GitHub issues are more aimed at problems with QuTiP source code.

**Comment by ydennisy** [comment]
@mba5811 Did you ever figure out how to do this?

@BoxiLi `entropy_vn` is only a part of the calculation needed, specifically for a bipartite system we need:
- the von Neumann entropy
- the joint quantum entropy
- a quantum generalisation of conditional entropy

Would love some help with achieving this in Qutip :)

**Comment by hodgestar** [comment]
@ydennisy Would be happy to discuss adding quantum discord functions to QuTiP, but please open a separate issue for adding it to QuTiP (this issue was more of a "do you have a short script that"). The first thing to include in the issue would be some specific definition of what to implement (e.g. a function signature) and a link to a suitable reference for the implementation (e.g. a paper) so that there is something concrete to discuss.

**Comment by ydennisy** [comment]
hey @hodgestar - sure will be happy to provide the above!
