### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by MrRobot2211** [qutip/qutip#1457]
Hi, I was wonfering if the first task in the wiki https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2020 would still be considered an interesting contribution? since it does not appear to be completed.

**Comment by BoxiLi** [comment]
Hi @MrRobot2211,

indeed that project is still open, see https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2021#1-error-mitigation-in-qutip. However, compared to last year, the workload is reduced because this year GSoC reduces the required working time (now 175h in total). If you are interested in the part that is removed (e.g. concrete physical model), you are still welcome to draft a proposal according to your interest. It does not have to follow exactly the ideas proposed on the wiki page as long as it is a self-contained project and related to QuTiP.

@nathanshammah in case he has comments.

**Comment by MrRobot2211** [comment]
Hi @BoxiLi  thank you for your answer, sounds interesting. My idea was to start collaborating  as soon as possible, and then afterwards apply for GSoC,  is this ok by you? or should I take on another feature since this is reserved for GSoC?

**Comment by BoxiLi** [comment]
Collaboration is open all the time, that's what open-source is for ;) It is required that all applicants have interaction with the community before applying so it is also kind of mandatory. And it will significantly increase the success probability of the application. Just notice that works done before GSoC won't give a reduction of the working load during the GSoC period (Google will check the process).

**Comment by MrRobot2211** [comment]
Hi @BoxiLi I have been doing the literature/software review, should I post the summary somewhere or send it to the mentors? And  I will begin writing the plan for GSOC.  I have made this PR https://github.com/qutip/qutip/pull/1463 to fulfill the requirements and I am awaiting a review.

**Comment by BoxiLi** [comment]
Sounds good! If you want to check beforehand whether your proposal is indeed what the community would like to include in QuTiP. You can start by sending a skeleton of the proposal (e.g. a few lines of deliverables in bulletin points) to the related mentors by email.

**Comment by jakelishman** [comment]
Closing now on the basis that you _have_ made a significant contribution!  Further discussion of potential GSoC projects is probably best done by emailing the admins.
