### ISSUE TITLE
correlation_2op_1t() and spectrum() giving the physically incorrect result unless solver='es'

### ISSUE THREAD

**Issue by gsteele13** [qutip/qutip#1460]
**Describe the bug**
See discussion here:

https://groups.google.com/g/qutip/c/2lod1DuFZiE/m/y8Bj6dKHDAAJ?pli=1

To my surprise, my PhD student had this problem again today, I am a bit surprised nothing has been done about this. 

At least making `es` the default solver for correlation and spectrum, updating the docs to give a warning to only use the es solver (for now?), and maybe longer term figuring out why the other solvers are not handling it properly

**To Reproduce**

https://github.com/gsteele13/gary-exploring-qutip/blob/master/Correlations.ipynb

```
import numpy as np
import pylab as plt
from qutip import *

N = 5
w = 1 * 2 * np.pi              # 1 Hz oscillator frequency
Q = 40
kappa = w / Q

# Set up some operators
a = destroy(N)
n = num(N)
x = (a + a.dag())/np.sqrt(2)
p = -1j * (a - a.dag())/np.sqrt(2)
H = w * a.dag() * a

c_ops = []

psi0 = fock(N,0)
tlist = np.linspace(0, 10, 500)

corr = correlation_2op_1t(H, psi0, tlist, c_ops, x, x, solver='me')

wlist1, spec1 = spectrum_correlation_fft(tlist, corr)

plt.figure(figsize=(14,8))
plt.plot(tlist, np.real(corr))
plt.plot(tlist, np.imag(corr))
plt.show()

plt.figure(figsize=(14,8))
plt.plot(wlist1, np.abs(spec1))
plt.show()
```

**Expected behavior**
Correlation should have an imaginary component and quantum PSD should not be symmetric about f = 0

**Your Environment**
Software	Version
QuTiP	4.4.1
Numpy	1.17.4
SciPy	1.4.1
matplotlib	3.3.4
Cython	0.29.14
Number of CPUs	4
BLAS Info	INTEL MKL
IPython	7.9.0
Python	3.7.5 (default, Oct 25 2019, 10:52:18) [Clang 4.0.1 (tags/RELEASE_401/final)]
OS	posix [darwin]
Wed Mar 10 08:51:15 2021 CET

**Additional context**

**Comment by nwlambert** [comment]
hi gary,  thanks for making this an issue, i think it fell through the cracks on the google groups.  

I think the problem is with how the expectation values are calculated.  Mesolve() returns the correct states, but they are wrongly flagged with isherm=True, even when they are not actually hermitian, so when expect() is called it takes the real part.  I think this incorrect flagging happens here for the output states
https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mesolve.py#L520

and here for collating the expectation values
https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mesolve.py#L510
(where only the hermiticity of the operators are checked, not the state.   you can check this by setting x.isherm=False in your code example, which fixes everything)

@Ericgig is there any issue with just removing this isherm=True flag here, and fixing the hermiticity check in the expectation values output call? i guess all this is getting replaced with your solver rewrite anyway, but if not it might make a good ''first issue'' for gsoc?

**Comment by nwlambert** [comment]
> hi gary, thanks for making this an issue, i think it fell through the cracks on the google groups.
> 
> I think the problem is with how the expectation values are calculated. Mesolve() returns the correct states, but they are wrongly flagged with isherm=True, even when they are not actually hermitian, so when expect() is called it takes the real part. I think this incorrect flagging happens here for the output states
> https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mesolve.py#L520
> 

Actually sorry, this is just for the final state.  For the full output list this happens

https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mesolve.py#L503

where the mc-dm option forces an isherm=true for some reason?

**Comment by jakelishman** [comment]
`Qobj` has some fast-path constructors that are basically the solvers saying "this data is valid, just trust me", causing it to skip sanity checks.  There are a few slow points that can be skipped: copying unnecessary data, parsing/verifying the `dims` data, and determining the properties (`isherm`, `iscp`, etc).  All of those add on very non-negligible construction time, but at most points in QuTiP we _know_ the values when passing them.  Old-style code uses these magic "fast-path" constructors, but the new 5.0 branch gets rid of all of them - you can achieve much more, and more explicitly, by using the kwargs.

We still want to maintain passing `isherm` to `Qobj` when we know it for speed reasons, especially when we know the most common use of the `Qobj` created by `mesolve` is for finding expectation values.  However, you can set the value based on the hermicity of the input density matrix; if you're passed a true density matrix, you'll always get a Hermitian matrix out, whereas you'll generally be in an unknown state if you're not.  The test can be
```
def mesolve(H, rho0, tlist, ...):
    hermicity = rho0.isherm or None
    ...
    for t in tlist:
        output.states.append(Qobj(fdata, dims=dims, isherm=hermicity))
```
which forces `isherm=True` if that's _known_, but leaves it unset if not.  This is approximately how we handle things in 5.0, which is in part why we have huge reductions in `Qobj` construction time in the new version.

**Comment by Ericgig** [comment]
This is a little tricky, but yes this could be a good first issue.
With master using `fast="mc-dm"`, the `Qobj` constructor ignore `isherm` input.
Also, to add a hermicity check for the state in expect, you need to be careful about column-stacked dm.

**Comment by jakelishman** [comment]
Except for setting the type of the `Qobj` (which is deleted at the end of `Qobj.__init__`), there's no need for the 'mc' or 'mc-dm' fast-paths to exist in `Qobj.__init__` at all, even in `master`.  If we were to fix the handling of a passed `type` - nothing else is overwritten if passed explicitly - you could achieve all the same effects at approximately the same speed with correct application of the kwargs, such as
```python
Qobj(data, dims=dims, copy=False, type='oper', isherm=...)
```
providing `data` is actually of a valid (`fast_csr_matrix`) format. Technically the `Qobj.data` attribute will be a new object that wraps the same numpy arrays as was passed, rather than the same `fast_csr_matrix`.

In various forms, `expect` already does check the Hermicity, that's why `mc-dm` is careful to set it to avoid recalculating it.  The expect functions in `qutip.expect` do this directly, and aren't aware of column-stacked density matrices - they'll just raise a TypeError.  `mesolve` and `mcsolve` now bypass the `Qobj` stage and go direct to Cython - in 5.0 it might not be a terrible idea to route everything back through the `Qobj` form, since the performance issues there are solved, and it's the natural central point of the code (and those parts are called from Python-space anyway, so no C concerns).

Here though, the problem is actually that the expectation generator in `mesolve` correctly calculates the dtype of the output expectation array using both the state and the expectation operator, but then it does it incorrectly in the loop, and passes the hermicity down to Cython using only the expectation operator, which promptly throws out the complex part.

So setting `fast='mc-dm'` in `Qobj` is a symptom of the same route cause as the problem here, rather than the cause itself.  At the start of `mesolve` we don't assume that the state is Hermitian, but then inside the integration loop we do - likely at some point someone spotted that we spent a whole bunch of time calculating the Hermicity and removed the test to get a speed-up.  We can still keep the speedup - if the output was created with a complex dtype, we can always safely say that we're passing in non-Hermitian operators, even if coincidentally at one timestep they happen to be anyway.

See https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mcsolve.py#L525-L529 and https://github.com/qutip/qutip/blob/d285e96b3afc61afd1deceef61d9635f9d9aa505/qutip/mesolve.py#L509-L511

**Comment by jakelishman** [comment]
And then I'll pretend that this comment doesn't exist at all, and we can go ahead and mark it has a good first issue.

**Comment by Ericgig** [comment]
For a first issue, it could be solved with little changes or by going down the rabbit-hole.
There could also be a discussion about always returning complex expectation values.

**Comment by jakelishman** [comment]
There's no rabbit hole - it's just a bug on line 511 of `mesolve.py` and 526 of `mcsolve.py`.  The output dtype is correctly calculated, it's just a bug in generating values for the output array.  There's a similar bug in the states output caused by the use of `fast='mc-dm'` that requires a more effort to fix, and should be at some point.

Having `qutip.expect` return real values for Hermitian operators and states I'd say is the correct behaviour.  It's by far the most common use-case, and it allows them to be directly plotted without generating a load of warnings.

**Comment by AGaliciaMartinez** [comment]
Hi everyone, I would like to solve this issue. Is anyone working on it already or should I just go for it?

**Comment by jakelishman** [comment]
No-one that I know of is working on it - we've left it open for somebody to come and have a starting issue to work with.  Thanks for taking it!
