### ISSUE TITLE
Wrong default weight parameter in steadystate function

### ISSUE THREAD

**Issue by davidschlegel** [qutip/qutip#1512]
**Issue**
In the codebase, the weight for setting the unit trace condition in the steadystate function should be set according to the documentation to the average value of the (nonzero) elements in the Liouvillian L, if not specified explicitly.

However in the code the weight is set as 
```python
 ss_args['weight'] = np.mean(np.abs(A.data.data.max()))
```
which is clearly different as it just set to the maximum value in the Liouvillian matrix A and hence the mean and abs are meaningless.

 I think this could be an overlooked mistake, or else just a mistake in the documentation of the parameter.

**Comment by jakelishman** [comment]
Thanks for reporting this.

This appears to have _always_ been an inconsistency between the documentation and the code.  These lines were added in one commit #166, with no reference to any changes.  I note at the moment that calling `max` on an array of complex (like this) finds the number with the maximal _real_ part, and then takes the absolute value of that.

I suspect that the `max` call got added in after everything else was written - if you remove that call, you would retrieve the documented behaviour, though I don't know enough about the numerical strategies to know which method is safer; I don't know whether we should change the documentationi or the behaviour. @nwlambert might be better placed to answer that.

**Comment by davidschlegel** [comment]
Thanks for the swift reply.
I am writing a similar code from scratch and so, I was wondering what qutip is using.
Perhaps there is some literature about this. But I guess setting a large weight makes the first row too dominant for iterative solvers, which could be the case in the current implementation.

**Comment by nwlambert** [comment]
I think a fix for this was proposed in this PR https://github.com/qutip/qutip/pull/1275  but that fix seems to still take the max over absolute values, so maybe is still inconsistent with documentation?

I also don't know  if there is a  reason to choose one over the other, I am not super familiar with the iterative solvers.     Could just be a typo or some unfixed testing,  particularly since it makes taking the mean completely pointless.

David's logic for the iterative solvers sounds like a good reason to revert it to the documented case.   If there is still some uncertainty we could ask paul (if he remembers!).
