### ISSUE TITLE
Broken links to source code in API documentation 4.4 due to underscore(_)

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1531]
In the latest documentation build, 4.4, the links to source code in the [API documentation](http://qutip.org/docs/latest/apidoc/apidoc.html) do not work.  
An example is the `Qobj` [source] link [in this page](http://qutip.org/docs/latest/apidoc/classes.html#qobj) that takes to this broken link, http://qutip.org/docs/latest/_modules/qutip/qobj.html#Qobj. 
The link is broken because it takes to `latest/_modules` instead of `latest/modules`, see for example the working link in 4.3, http://qutip.org/docs/4.3/modules/qutip/qobj.html#Qobj, or even the correct http://qutip.org/docs/latest/modules/qutip/qobj.html#Qobj.  

Any help appreciated in fixing this in Sphinx, I think in `sphinx-apidoc`, cc @Ericgig @quantshah @ajgpitch @tehruhn @BoxiLi (pinging you as only Alex watches this repo and you all played with Sphinx recently).

**Comment by Darshil9120** [comment]
I would be interested in taking up this issue. As far as, I understand we just have to fix broken links by using links that do not have underscore in it, right?

**Comment by hodgestar** [comment]
@Darshil9120 I actually don't know what the "correct" fix should be. The links are actually correct in the documentation source, but Jekyll, which is used to generate qutip.org, ignore folders with leading underscores, so they underscores need to be removed from the folders and the links to them.

There is a script https://github.com/qutip/qutip.github.io/ called `docs/remove_leading_underscore.py` that does this.

I'm inclined to close this issue for now unless since we have a solution, but I'm happy to reopen it if someone has a good concrete suggestion (I think change the Sphinx defaults is a bit of a mess, but maybe we could configure Jekyll to not ignore some specific folders -- e.g. all folders with leading underscores that are under the docs folder).
