### ISSUE TITLE
Eigenvalues of permutational invariant Liouvillian (PIQS)

### ISSUE THREAD

**Issue by HumpyBlumpy** [qutip/qutip#1545]
Hello,

How can one find the eigenvalues of the Liouvillian built using PIQS ?
I could not find it in the documentation, so I am not sure if it is implemented or not.
If not, I would be grateful for any tips on how to do it myself.

Thanks

**Comment by nathanshammah** [comment]
The eigenvalues can be found with the typical functions present in qutip, such as `eigenenergies()` and `qutip.eigenstates()`. However, there can be some spurious eigenvalues, as detailed in this issue, #993. Only the steadystate, with eigenvalue 0, is assured to be correct. If you are just interested in the Liouvillian gap only, that should be fine. 

Another faster and more stable technique that can be used in the case that only local dissipation processes are present (while the Hamiltonian is long range), is that of calculating the "antigap": since an additional weak PT symmetry is present, the symmetry of the Liouvillian spectrum in the complex plane can be exploited by just calculating the two largest eigenvalues.
