### ISSUE TITLE
`tlist are not compatible` when using collapse operators in `mesolve`

### ISSUE THREAD

**Issue by julien-bremont** [qutip/qutip#1560]
Hi,
I'm trying to use `mesolve` using a sampled hamiltonian to be interpolated (_list array format_ according to [the doc](https://qutip.org/docs/latest/apidoc/functions.html?highlight=mesolve#module-qutip.mesolve)) with a `tlist` that isn't the time list `times` of the Hamiltonian coefficients, but a sublist `eval_times` of `times`. This method works fine and returns the results at `eval_times` when `c_ops=[]`, but if I specify collapse operators, I get a `tlist are not compatible` error.

Here is an example of what I'm saying.
```python
times = np.linspace(0, 1, 100)
x = np.cos(2*np.pi * times)
eval_times=times[0:-1:3]
rho = qutip.basis(2, 0).proj()
ham = qutip.QobjEvo([[qutip.sigmax(), x]], tlist=times)
qutip.mesolve(ham, rho0=rho, tlist=eval_times, c_ops=[]) # works fine
collapse = [qutip.qeye(2)] 
qutip.mesolve(ham, rho0=rho, tlist=times, c_ops=collapse) # works fine as well
qutip.mesolve(ham, rho0=rho, tlist=eval_times, c_ops=collapse) # raises `tlist are not compatible` error
```

Do you have any idea what might cause this behaviour ? I believe this might be an issue with the `mesolve` solver, since when you don't specify `c_ops`, you use `sesolve`.

**Comment by jakelishman** [comment]
I haven't checked, but I'd bet it's because we construct a new Liouvillian `QobjEvo` on entry to `mesolve` with collapse operators.  If so, this is definitely a bug - we should have detected that the collapse operators have no time-dependence, so don't need to overwrite the `tlist`.

As a temporary work-around, you can construct the Liouvillian directly and pass it to `mesolve`:
```python
liouvillian = qutip.liouvillian(ham, collapse)
qutip.mesolve(liouvillian, rho, eval_times)
```
which should work fine for now.

**Comment by julien-bremont** [comment]
Thanks a lot ! It works indeed.
