### ISSUE TITLE
Inconsistent values for harmonic oscillator

### ISSUE THREAD

**Issue by subimal** [qutip/qutip#1587]
Hello everybody,
I am using QuTiP 4.6.2. I created the Hamiltonian for a harmonic oscillator in terms of
1) the momentum and position operator
2) the number operators

The first case runs into trouble always whereas the second does not.

The issue: When I use the momentum and position operator to create the Hamiltonian, the eigenvalues of two states in the middle of the series of states come out to be equal. this happens no matter how many Hilbert space levels I use. This issue is not there when I use the creation and annihilation operators. I should be getting identical results in both cases. Can someone point out where have I gone wrong? The code below is copied from my interpreter to show the results.
```python
>>> import qutip as qt
>>> N = 10 # no. of states
>>> om = 1
>>> p = qt.momentum(N)
>>> x = qt.position(N)
>>> H = 0.5*(p*p+ om*om*x*x)
>>> evals, evecs = H.eigenstates()
>>> print("evals: ",evals)
evals:  [0.5 1.5 2.5 3.5 4.5 4.5 5.5 6.5 7.5 8.5]
>>> # evals[4] and evals[5] are equal (Why?)  <<< The error
>>> evecs[4]==evecs[5]
False
>>> # now let us use the creation and annihilation operators to create the Hamiltonian
>>> ad = qt.create(N)
>>> a = ad.dag()
>>> H1 = (ad*a + 0.5)*om
>>> evals1, evecs1 = H1.eigenstates()
>>> print("evals1: ",evals1)  # <<< No trouble here
evals1:  [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
>>>
```

I would appreciate any input to fix my understanding. I am not opening a bug report because I am not sure. 

With my best regards
Subimal Deb

**Comment by nwlambert** [comment]
Hi Subimal,

This happens because of the truncation of the Fock space.  You can see a related discussion here 
https://groups.google.com/g/qutip/c/DD6z8kYUU1I/m/k48XZS1AAgAJ

But in short, with truncation there is always an error in the commutators, so for truncating the Fock states at N photons,  I think you find that [a,a.dag()] = \sum_{n=0}^(N-1) |n><n| - N|N><N|   (you can check this by writing out these operators as projectors onto fock states, you will notice a*a.dag() is missing a term due to the truncation that should cancel with a term in a.dag()*a)

Similarly putting the creation and annihilation operators into the position/momentum definition of the Hamiltonian, you find H = sum_{n=0}^(N-1)(n+0.5) |n><n| + N/2 |N><N|.   Hence,  since you truncated at 9 photons in your example, there is a degeneracy of the 4.5 eigenvalue.

I am not sure if there is much can be done about this in general, perhaps the discussion I linked above might be useful.  The main message I suppose is always take a larger cut-off than you think you might need, particularly if you are relying on the commutation relations to simplify things for you (which, given your example, can be a bad idea some times!). 

 I guess there is an interesting question about what is the best practice in these things, e.g., if you have a non-linear model, what form is it best to put it in before moving to a truncated basis?  given your example, I would expect  something like normal ordering to be better.

**Comment by hodgestar** [comment]
@subimal Closing this for now because I think @nwlambert has given a good explanation, but please feel free to reopen or comment further as needed.

**Comment by subimal** [comment]
Hi Neill,

Thanks a lot for your answer. I did think the issue was with truncated Fock space but did not expect the 'error' would show up right in the middle of the eigenspectrum. I was expecting it somewhere towards the end of the spectrum. The explicit explanation is very helpful.

As you pointed out, it would indeed be useful to have a list of ground rules (like normal ordering you mentioned) 
* for new users
* for those handling a problem where a closed form solution is unknown.

I will check if the suggested normal ordering approach is helpful in other cases also. Hopefully it should be alright if I report my findings as a followup comment in this thread.

With my best regards
Subimal Deb

**Comment by hodgestar** [comment]
> I will check if the suggested normal ordering approach is helpful in other cases also. Hopefully it should be alright if I report my findings as a followup comment in this thread.

Thanks @subimal, reporting your findings in a followup comment would be perfect.
