### ISSUE TITLE
Exception: ODE integration error: Try to increase the allowed number of substeps by increasing the nsteps parameter in the Options class

### ISSUE THREAD

**Issue by soumyasrtk** [qutip/qutip#1623]
I get this error for anything less than nsteps = 1000000 (I've tried 5000, 10000, 50000, 100000, 500000) while using mesolve to get the dynamics of the system according to the Lindblad ME.
Details - It is a two qubit model, with both qubits coupled to baths and with inter-qubit coupling present. The solution for unit time with 100 divisions takes about 10 min but for any time interval greater than 1, I keep getting this error even with nsteps = 1000000, 5000000. Anything greater than that takes >2 hours to evaluate.

```python
import numpy as np
import matplotlib as plt
from qutip import *
from cmath import *
```
Initial State:
```
initialstate=tensor(fock_dm(2,0),fock_dm(2,0))
```
Hamiltonian:
```
epsilon=1
g=0.025
sigmaplus=0.5*(sigmax()+1j*sigmay())
sigmaminus=0.5*(sigmax()-1j*sigmay())
H=0.5*epsilon*(tensor(sigmaz()+qeye(2),qeye(2))+tensor(qeye(2),sigmaz()+qeye(2))) + g*(tensor(sigmaplus,sigmaminus)+tensor(sigmaminus, sigmaplus))

```
Jump operators:
```
gamma1=0.1
gamma2=0.05
T1=2
T2=0.05

diss_coeff=[cmath.sqrt(gamma1*(1/exp(epsilon/T1)-1)),cmath.sqrt(gamma1*exp(epsilon/T1)*(1/exp(epsilon/T1)-1)), cmath.sqrt(gamma2*(1/exp(epsilon/T2)-1)), cmath.sqrt(gamma2*exp(epsilon/T2)*(1/exp(epsilon/T2)-1))]

diss_oper=[diss_coeff[0]*tensor(sigmaplus, qeye(2)),diss_coeff[1]*tensor(sigmaminus, qeye(2)),diss_coeff[2]*tensor(qeye(2),sigmaplus), diss_coeff[3]*tensor(qeye(2),sigmaminus)]
```
Time steps:
```
tlist = np.linspace(0, 1, 100)
```
Using mesolve:
```
dynamics=mesolve(H, initialstate, tlist,diss_oper, options=Options(nsteps=10000)) 
```
Note: nsteps=1000000 in the line above evaluates in 7 min

Ideally, I would like to solve for time in the range (0, 400) but in the worst case, time range (0,250) will do (with about 1000 divisions). But, increasing nsteps is not an option because the evaluation takes too long. Are there any changes I can make for faster evaluation?

**Comment by BoxiLi** [comment]
Pure numerically speaking, the last `diss_coeff` is a way larger than the others.
```python
>>>diss_coeff
[0.19836061612310207j,
 0.25470007277190326j,
 0.223606797519535j,
 4925.267477050309j]
```
With this large frequency, if you want to solve the dynamics using ODE, I don't think there is a way to make it faster. You have to either simplify your model mathematically, or, because there is no time dependency in your system, use the (deprecated) `essolve` that computes the dynamics using eigenvalues.

Thinking about the physics, the T2 time is much smaller than your `tlist`, the system has already fully decohered.

PS: @jakelishman It seems that the `essolve` does have some use-cases? Like in small systems for verification perpose. I remember there is another PR that also mentions it. As we deprecated it, I'm wondering if there is an efficient alternative in QuTiP?

**Comment by soumyasrtk** [comment]
@BoxiLi Thank you, that was the root of the problem. I'd made an error while defining the list of coefficients. It's working fine now.
That last coefficient was not supposed to be that large.
