### ISSUE TITLE
QobjEvo with propagator

### ISSUE THREAD

**Issue by petergthatsme** [qutip/qutip#1672]
Looking at the latest source code, it seems like `QobjEvo` objects are not supported by the `propagator` function.

This problem is tangentially mentioned in the issue: https://github.com/qutip/qutip/issues/1482
... although that issue has been closed, so I'm just wondering if this is actually on the list of items to be implemented?

thanks!

**Comment by hodgestar** [comment]
@petergthatsme #1482 contained a work around. As @Ericgig mentioned, we've have this on the list of things to for QuTiP version 5 (which is in progress in the `dev.major` branch).

The root cause is that all of the solver related functions had their own lists of which of the many things `H` can be -- a `Qobj`, a list, a function, etc -- that they support. Over the years of QuTiP's existence these got out of sync with each other. QuTiP version 5, everything will support QobjEvo and under the hood any of the other things that are not QobjEvo or Qobj will immediately be translated into a QobjEvo.

I'll leave this open and tag it with the QuTiP 5 milestone so that we definitely don't forget it in QuTiP 5 (although that seems unlikely).

**Comment by hodgestar** [comment]
P.S. If the workaround in #1482 doesn't work for you, please feel free to comment more.

**Comment by petergthatsme** [comment]
Thanks for your comment!
I somehow missed the note that it's on a TODO for the next major release - that's great, as it will make things a bit more consistent.
