### ISSUE TITLE
Bug in sesolve and mesolve states

### ISSUE THREAD

**Issue by Hosseinyeganeh** [qutip/qutip#1686]
I have simple code for Time evaluation, with ```mesolve``` and ```sesolve```I consider two time list as``` t1=[0,5,10]``` and ```t2=[0,10]```.But I get different states in``` t=10``` in two case 

```python
from qutip import*
import numpy as np
H= 2*np.pi * 0.1 * sigmax()
psi0 = basis(2, 0)
t1=[0,5,10]
t2=[0,10]
result1 = sesolve(H, psi0, t1)
result2 = sesolve(H, psi0, t2)
r1=result1.states[2]
r2=result1.states[1]
if r1==r2:
    print('True')
else:
    print('False')

```
If you run code you get ```False```. This difference between to case is  ```1.1620088200000005e-6j``` but it's important in many context such as   measure entanglement in general Form.
Best

**Comment by jakelishman** [comment]
You can control the tolerance of the output of the solvers with the `qutip.Options()` class, in particular the parameters `atol`, `rtol` and `nsteps`.

It's highly unlikely that you'll ever get them to be _exactly_ equal due to the realities of floating-point.  A more relevant measure is the size of the overlap `r1.overlap(r2)`.  Again, this will never be exactly 0, but by setting the tolerances of the solvers suitably, you can bound it to an acceptable value.

This is unfortunately just one of the realities of numeric computing - floating-point calculations accumulate error, and it's up to the user to specify what level of error is tolerable.

**Comment by hodgestar** [comment]
@Hosseinyeganeh I think Jake has explained nicely why you get the results you do. Closing this issue for now, but please feel free to continue the discussion if needed.
