### ISSUE TITLE
Need for code refactoring?

### ISSUE THREAD

**Issue by Chasmiccoder** [qutip/qutip#1729]
**Is your feature request related to a problem? Please describe.**
I noticed that QuTiP got a C in the [Code Climate Report](https://codeclimate.com/github/qutip/qutip) in terms of readability and maintainability.

Also, apart from the FIXMEs and the TODOs, there's many pep8 related issues (which can be fixed easily)

I understand that this is not top priority stuff, but it might help in the long run.

**Additional context**
For example, in the file `qutip/qip/compiler/cavityqedcompiler.py`, the functions   
`sqrtiswap_compiler` and `iswap_compiler` are very similar, and under sqrtiswap_compiler, it says to use iswap_compiler instead.

In the same file `rz_compiler()` and `rx_compiler()` have the exact same code barring a string "sz" and "sx" which could be
passed as an argument.
[link to the report for this file](https://codeclimate.com/github/qutip/qutip/qutip/qip/compiler/cavityqedcompiler.py/source#issue-99d25ce9cdbd1dc34f5899352286755d)

**Comment by BoxiLi** [comment]
Hi @Chasmiccoder, indeed the qutip source code is not yet fully pep8 compatible, although we are pushing towards it. In general, we try to avoid large-scale PR that only fix style issues like running `pycodestyle`, because it may introduce lots of conflicts if someone else is also working on the same code.

That said, refactoring code for better maintainability is of course helpful in the long run. It would be good to check the development version. I believe we are doing a better job there. The newest version of `qutip` can be found on the `dev.major` branch of qutip https://github.com/qutip/qutip/tree/dev.major. And the master branch of `qutip-qip` https://github.com/qutip/qutip-qip. The package `qutip-qip` is a separate repository that serves as a replacement of the module `qutip.qip`, because the module will be removed in qutip-v5 (`dev.major`). The duplication you mentioned should already be fixed there. But of course there are still other imperfections if you are interested.

**Comment by hodgestar** [comment]
@Chasmiccoder I agree with @BoxiLi that we don't want to do a big refactor, especially of the older 4.6 and 4.7 releases.

I would like to add some code style checkers like `pyflakes` , `black` (or `blue`) and `isort` to our CI system on the `dev.major` branch, initially excluding all the files and then slowly including more and more files in the checks as we fix them.

I'm going to close this issue for now, but if you would like to tackle adding, e.g., `pyflakes` to `dev.major` that would be awesome.
