### ISSUE TITLE
Add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [qutip/qutip#1742]
### Problem Description

I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Manually going through all the required style conventions and guidelines would be a hassle.

### Proposed Solution

Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

**Comment by hodgestar** [comment]
I would rather have the styling checks part of CI than pre-commit.

Pre-commit hooks are a nice way to automate repetitive tasks, but for coding conventions, each developer tends to have their own setup (e.g. I would run black or pyflakes as a plugin in my editor, so that I get immediate feedback or fixes long before making a commit).

Pre-commit hooks are also a poor choice for checking that coding style is followed, because developers will have different operating systems, difference versions of Python, black, pyflakes, etc, etc and so there are certain to be differences between what is considered correct by the scripts run by different developers.

Finally, there are many valid reasons to commit broken code into branches, and I would not want to prevent that.
