### ISSUE TITLE
Set up towncrier for managing the changelog.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip#1894]
### Problem Description

Currently the most time consuming part of making releases is managing the change log (#1055 , #1108, #1533). In addition to the time taken, the release manager is often poorly placed to write change log entries for the PRs involved (the PRs might have been merged some time ago, and the release manager might not have been the author).

### Proposed Solution

[Towncrier](https://pypi.org/project/towncrier/) is a Python package used by Python itself and many other libraries to manage the change log.

I propose that we configure towncrier and ensure that each PR adds a towncrier entry.

This includes:
- [x] Add suitable towncrier configuration to the respository.
- [x] Update the release documentation with instructions for using towncrier to update the change log.
- [x] Update the development documentation to include the requirement to add towncrier entries for each PR.
- [x] Update the GitHub PR template to mention the requirement to add a towncrier entry.
- [x] Add a check to the GitHub action tests workflow that checks that a towncrier entry was added.

### Alternate Solutions

There are a few other tools that do similar things to towncrier, and we could use one of those instead if they are better.

I would recommend that we not roll our own solution. The problem is fairly simple, but writing and documenting our own solution and fixing the inevitable bugs is a lot of work. Plus, I would prefer to have a solution that has already made choices that work, rather than us having to make all of those choices ourselves.

**Comment by divshacker** [comment]
Hey, I can try working on this issue.

**Comment by trentfridey** [comment]
Hi - I think I might have a solution for this issue in #1927.  Setting up the utility was pretty straightforward, but I am not sure on how best to shape the process around using it. There are two issues that I foresee:
- Generating a news fragment when making a PR:
 In order to reference PRs in the changelog, you have to pass the PR number to 
 `towncrier create <PR number>.<change type>` 
 So the process would be:
   1. Make draft PR
   2. Get PR number
   3. run towncrier create with PR number and commit & push resulting news fragment to PR
   4. Mark PR as ready

A way around this extra step is to reference the issue number, but you may not want that.
- When generating changelogs for releases, towncrier needs to be passed the version number in one of three ways (from the documentation):
  - For Python 2/3 compatible projects, a __version__ in the top level package. This can be either a string literal, a tuple, or an [Incremental](https://github.com/hawkowl/incremental) version.
  - Manually passing --version=<myversionhere> when interacting with towncrier.
  - Defining a version option in a configuration file
 Since there's no __version__ string or configuration file, I guess we would use the second option when calling `towncrier build`?

I'm not sure what the intended flow is for this and I didn't feel comfortable changing the release process, so perhaps someone can advise?

**Comment by hodgestar** [comment]
@trentfridey Thank you for opening the PR. I will review it a bit later, and attempt to answer your first question here once I have.

In answer to your second question, I think the minimal approach, and the one we should take now, is to add running `towncrier build` to the steps in creating or updating the release branch (i.e. the human doing the release would run it and push the result). Later once we have some experience using it, we can consider automating the release process a bit more somehow.
