### ISSUE TITLE
Time evolution based on the Lindblad master equation not CPTP

### ISSUE THREAD

**Issue by dkweiss31** [qutip/qutip#1901]
### Bug Description

Time evolution based on the Lindblad master equation for a time-independent Hamiltonian is guaranteed to be completely positive and trace preserving (CPTP). However, the flag `iscptp` returns `False` for the Liouvillian when calling `propagator` for a time-independent Hamiltonian and including a collapse operator.

### Code to Reproduce the Bug

```shell
from qutip import sigmaz, qeye, propagator, tensor, sigmam

c_ops = [0.00001 * tensor(sigmam(), qeye(2))]
H0 = tensor(sigmaz(), qeye(2)) + tensor(qeye(2), sigmaz())
H = H0
prop = propagator(H, 1.0, c_ops)
print(prop.iscptp)
```

### Code Output

```shell
False
```

### Expected Behaviour

I expect `prop.iscptp` to be `True`

### Your Environment

```shell
QuTiP Version:      4.7.0
Numpy Version:      1.21.2
Scipy Version:      1.7.1
Cython Version:     0.29.23
Matplotlib Version: 3.4.2
Python Version:     3.7.7
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
```

**Comment by Ericgig** [comment]
The issue is with numerical error: the default tolerance for the computation of the propagator is `1e-8`, but the tolerance for `iscptp` is `1e-12`.

You can improve the precision of the propagator by passing `options=Options(atol=1e-14, rtol=1e-14)`. These precisions are per internal step, not for the full evolution.  You can also lower the requirement for `iscptp` with `qutip.settings.atol = ...`.

**Comment by dkweiss31** [comment]
I see! That fixes the issue, thank you very much
