### ISSUE TITLE
The time-dependent Hamiltonian cannot call the function liouvillian() of the Dicke class

### ISSUE THREAD

**Issue by Ni2310** [qutip/qutip#1928]
I'm a student using qutip.piqs for the first time, don't know if there is an example of this kind of problem, for the time-dependent Hamiltonian  call the function liouvillian() of the Dicke class

**Comment by Ericgig** [comment]
Dicke class does not support list based time-dependent Hamiltonian.
But if the Hamiltonian is a `QobjEvo`, it should work: `qutip.piqs.Dicke(N, hamiltonian=qutip.QobjEvo(H_td), emission=...)`
Otherwise you can use the Dicke class to compute the dissipation part and use `mesolve`:
```
dicke = qutip.piqs.Dicke(N, hamiltonian=None, emission=...)
qutip.mesolve(H_td, ..., c_ops =dicke.liouvillian())
```
For more help, please use the google groupe: https://groups.google.com/g/qutip.
