### ISSUE TITLE
Discrepancy between mesolve and general_stochastic

### ISSUE THREAD

**Issue by tnadolny** [qutip/qutip#1935]
### Describe the Issue!

Hi,

I would expect mesolve and the corresponding implementation with a d1 term in general_stochastic to give the same result when the stochastic evolution (d2) is set to zero. However, this is not the case (see the following minimal working example).

Am I mistaken in the assumption that the d1 term should give the same deterministic evolution as what is calculated by mesolve, or is there another issue?
 
(this is maybe similar to Issue #1379)
Thanks! 

```python
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

times=np.linspace(0,10,100)
psi0 = (basis(2,0)+basis(2,1)).unit()
rho0=ket2dm(psi0)

H=sigmaz()*0 # discrepancy also for sigmaz()*1
c_ops=[sigmaz()*0.5]

def d1(t,rho_vec): 
    l=liouvillian(H,c_ops=c_ops)
    return l.data*rho_vec # this should give the same evolution as below in mesolve?

def d2(t,rho_vec):
    return np.array([rho_vec*0]) # switching off the stochastic part

me_sol = mesolve(H,rho0,times,c_ops=c_ops,e_ops=[sigmax()])

gs_sol = general_stochastic(rho0,times,d1=d1,d2=d2,len_d2=1,e_ops=[spre(sigmax())],
                            ntraj=1,nsubsteps=10) # same for nsubsteps=100

plt.figure()
plt.plot(times,me_sol.expect[0],label='mesolve')
plt.plot(times,gs_sol.expect[0],label='general_stochastic')
plt.legend()
plt.xlabel('time')
plt.ylabel('<X>')

# Total run time:   0.30s
```

![grafik](https://user-images.githubusercontent.com/104072493/173811282-a67100e6-8f18-4970-9e1a-62b2d11f2214.png)

**Comment by Ericgig** [comment]
For these kind of problems, you should use `smesolve`, you can see what equation it solve [here](https://qutip.org/docs/latest/guide/dynamics/dynamics-stochastic.html#stochastic-master-equation).

`general_stochastic` should be used only in last resort. While it allow to use the stochastic solver mechanic with your own functions, it use the same options and mix of `Qobj`, `Qobj.data` and `array`, etc., without the layer to glue everything together...

Here, the issue is that it use the same options as `ssesolve` and `smesolve`, which per default normalize the state before computing the expectation values, but do not know that it's supposed to be an density matrix, thus normalizing the state as if it was a ket...  You can pass `normalize=False` to `general_stochastic` to obtain results closer to `mesolve`, but I would recommend not to use `general_stochastic` in the state it is now.

**Comment by tnadolny** [comment]
Thanks for your reply!
The above code was of course only an example for demonstration purposes. The reason to work with `general_stochastic` is to add a term $ dρ(t)= ... + i f(t) [\sigma_z,ρ(t)]dW(t)$ to the stochastic evolution of the density matrix. Can you recommend a way to do this, without running into the issues you mentioned for `general_stochastic`? I don't see a way how to do it using `smesolve`.

**Comment by Ericgig** [comment]
You can set `sc_ops=[1j*sigmaz(), f]]` in `smescolve`.

The computation smesolve does is:
```
def d2(t, rho):
    drho = sc_ops(t) * rho + rho * sc_ops(t).dag()
    drho -= drho.tr() * rho
    return drho
```
Which is what you want:
```
def target_d2(t, rho):
    return 1j * f(t, None) * (sigmaz() * rho - sigmaz() * rho)

rho = rand_dm(2)
t = np.random.rand()
d2(t,rho) == target_d2(t,rho)
```
But it add a dissipation term in d1 and if you don't want it, there is no easy way around it...

**Comment by tnadolny** [comment]
Thanks again for your helpful reply!
I was able to use this and correct for the extra dissipation term in d1 by adding Lindblad dissipator term with opposite sign to the Hamiltonian part. In this particular case:
``` python
def time_dependence(t,args): return f(t,args)**2

H_ops = [H_original,[ - lindblad_dissipator(sigmaz()),  time_dependence]]

smesolve(H_ops,...,sc_ops=[1j*sigmaz(), f]],...)
```
