### ISSUE TITLE
concurrence measure does not work for density matrices

### ISSUE THREAD

**Issue by epelofske-LANL** [qutip/qutip#2058]
### Bug Description

The concurrence measure does not work with density matrix objects.

### Code to Reproduce the Bug

```shell
import qutip

dm = qutip.maximally_mixed_dm(4)
print(dm)
print(qutip.entropy.concurrence(dm))
```

### Code Output

```shell
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25]]

    raise Exception("Density matrix must be tensor product of two qubits.")
Exception: Density matrix must be tensor product of two qubits.
```

### Expected Behaviour

One of two things is happening:
1. The concurrence method is not compatible with the density matrix Qobj objects. I am not certain why this concurrence method requires [[2, 2], [2, 2]] dimensions instead of [4,4] if the concurrence method is acting on 2 qubit systems.
2. The density matrix generators are not producing matrices which are consistent with the qutip required format. I tried this on other matrices by just casting numpy arrays to Qobj objects and I got the same error. 

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.21.5
Scipy Version:      1.9.1
Cython Version:     0.29.32
Matplotlib Version: 3.5.2
Python Version:     3.9.13
Number of CPUs:     10
BLAS Info:          OPENBLAS
OPENMP Installed:   False
```

**Comment by hodgestar** [comment]
Hi @epelofske-LANL.

This behaviour in QuTiP is intentional for the following reason: If the dims of the system are `[2, 2]` then it's unambiguous how the system should be partitioned into two parts because the dims specify what the two parts. If the dims are `[4]` then one could divide the system in multiple ways depending on how one considers the four basis vectors.

If one knows that the four basis states are `00`, `01`, `10`, `11`, one can override the dims by writing `dm.dims = [[2, 2], [2, 2]]` or `qutip.Qobj(dm, dims=[[2, 2], [2, 2]])`.

Hope this helps. I agree this could be made more intuitive. Perhaps `maximally_mixed_dm` should allow specifying `dims` too instead of just `N`.

I'm closing this issue for now, but please feel free to continue the discussion in the comments.
