### ISSUE TITLE
solve function signature don't match

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2489]
### Problem Description

Some the the `??solve` functions inconsistent signature:
Almost all of them start with `H, state0, tlist`, the collapse if used, expectation, `args` and finally options.

But 
- For `brmesolve`, `c_ops` comes after `e_ops`.
- For HEOM: the bath is between the Hamiltonian and the initial state.
- Stochastic solver have `e_ops` `options` and `args` as keyword only.
- `ntraj` is positional for `mcsolve`, but keyword only for stochastic solver.
- Solver specific parameters are between `e_ops` and `args` for floquet, between `args` and `options` for bloch redfield and after `sc_ops` in stochastic.

### Proposed Solution

Make `e_ops`, `args`, `options` and `ntraj` keyword only from 5.3, with a warning message from 5.1.

This would make is all signatures, except HEOM, match.

For HEOM, the `bath` and `max_depth` should be swapped for the `state` and `tlist`.

**Comment by hodgestar** [comment]
For the HEOM the bath is part of the description of the system evolving, which is why it is next to the Hamiltonian. It might be nice to be able to specify the bath and the Hamiltonian as a single parameter, but not sure how easy that is to do without breaking the API a bit (not entirely against doing so). `max_depth` could also be considered part of the system description.

+1 on making some arguments keyword only.

**Comment by Ericgig** [comment]
With that logic, we could say that the `c_ops`, `sc_ops` etc. are part of the system and should come right after the Hamiltonian. While this feels right to me, it would break too many code...

Since HEOM is new and somewhat niche, I think it would be more doable to bring in line with other, even if it's the worst order. But it would be hard to do it smoothly, so it may be best to just let it be.

**Comment by hodgestar** [comment]
A bit of future thinking: It might be nice to introduce a `System` object which is the Hamiltonian plus any c_ops, sc_ops, baths, etc.
