### ISSUE TITLE
State returned from mcsolve and mcsolve_f90 has different quantum object structure

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip#330]

**Comment by nonhermitian** [comment]
What exactly is the problem?

**Comment by kwyip** [comment]
the structure of the states returned are different. A subtle difference is mcsolve returns a representation of state wrapped with one more square bracket.

**Comment by nonhermitian** [comment]
I see the issue.  The mcsolver has the correct output format.   It is done that way so that if you change ntraj, the return values from the states does not change shape.  If ntraj > 1 then the results are the same when grabbing states from a given trajectory.  In the ntraj=1 case they are different.  It is a straightforward fix.

Thank you for pointing this out.  As it turns out, the mcsolve_f90 function will be a separate installation starting from QuTiP 3.2, so it is best to use the normal mcsolve function.

**Comment by nonhermitian** [comment]
This has been fixed in #335.
