### ISSUE TITLE
Warning message when os.environ['HOME'] is not defined

### ISSUE THREAD

**Issue by mivade** [qutip/qutip#365]
I am running a IPython/Jupyter Notebook via [supervisor](http://supervisord.org/) which does not export the `$HOME` environment variable (this is of course easily fixable). When importing qutip, I get the following warning message:

```
WARNING:qutip.settings:Error loading RC file.
Traceback (most recent call last):
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/qutip/__init__.py", line 138, in <module>
    os.environ['HOME'], ".qutiprc"
  File "/home/mvd/miniconda3/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

Since this is just a warning, does it mean that there are no problems, or will it have some effects?

**Comment by cgranade** [comment]
This is an interesting bug, thanks for raising it! Roughly, QuTiP looks at ``$HOME`` to find where the ``qutiprc``configuration file. If QuTiP can't find it, it will raise a warning and proceed with defaults, so that shouldn't adversely affect you unless you've set some flags like ``debug=True``. That said, we should definitely raise a less intimidating warning when ``$HOME`` is unset.

**Comment by cgranade** [comment]
With #366 merged in, I think this issue has been addressed. Thanks!
