### ISSUE TITLE
Please add the 'test' target to setup.py

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#410]
Maybe this:
```
import qutip.testing as qt
qt.run()
```
?

**Comment by cgranade** [comment]
The ``test`` subcommand for ``setup.py`` depends on ``setuptools``, rather than just ``distutils``. We don't want to require ``setuptools``, however, so I think the best strategy is to try and import it but fall back to ``distutils`` if we can't. I'll post a PR soon that will follow this strategy. Hopefully, that should make it a bit more convenient to run unit tests.
