### ISSUE TITLE
Lindblad Equation with non-Hermitian Hamiltonian.

### ISSUE THREAD

**Issue by TanMath** [qutip/qutip#416]
Does mesolve for Lindblad Equation support non-Hermitian Hamiltonians. Currently, I am working on some code with three Hamiltonians added up for a total Hamiltonian. One of these, a Hamiltonian to account for trapping in the system, causes the trace not to be preserved -> non-Hermitian. Now, currently, the simulation acts like this trapping Hamiltonian vanishes so I am thinking maybe mesolve cannot support non-Hermitian Hamiltonians? If so, can support for this be added?

**Comment by nonhermitian** [comment]
There is nothing in the code that should prevent one from doing that, provided that the problem is still in Lindblad form.  The mesolve routine does not normalize or check the trace for the return density matrices, so I naively think that it should work.

**Comment by TanMath** [comment]
@nonhermitian Technically speaking, the Hamiltonian in the Lindblad Equation is Hermitian, so that is why I am asking. So it doesn't check if the Hamiltonian is Hermitian? Does it assume that it is Hermitian but doesn't check?

**Comment by nonhermitian** [comment]
It does not check for hermicity. But as you suggest the equation itself is designed for a valid Hamiltonian

Sent from Outlook Mobile




On Thu, Jan 14, 2016 at 1:27 PM -0800, "TanMath" <notifications@github.com> wrote:












@nonhermitian Technically speaking, the Hamiltonian in the Lindblad Equation is Hermitian, so that is why I am asking. So it doesn't check if the Hamiltonian is Hermitian? Does it assume that it is Hermitian but doesn't check? 


—
Reply to this email directly or view it on GitHub. 
 
  
   
   
  
  
 

 Untracked with 
 Trackbuster

**Comment by TanMath** [comment]
@nonhermitian so would it work for a non-Hermitian Hamiltonian or not?

**Comment by nonhermitian** [comment]
If no other change is required to the master equation besides the non-hermitian hamiltonian then yes. 

Sent from Outlook Mobile




On Thu, Jan 14, 2016 at 5:38 PM -0800, "TanMath" <notifications@github.com> wrote:












@nonhermitian so would it work for a non-Hermitian Hamiltonian or not? 


—
Reply to this email directly or view it on GitHub. 
 
  
   
   
  
  
 

 Untracked with 
 Trackbuster

**Comment by nonhermitian** [comment]
question answered.
