### ISSUE TITLE
Travis tests currently unpredictable

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#430]
We have a number of pull requests that are all nice fixes and enhancements, however we are delaying merging because of travis test failures. I can't see how any of these pull request can be an underlying cause:
#421 
#422
#428
#429
So I will merge all these. We can then investigate what is causing some of the tests to fail under this issue.

**Comment by cgranade** [comment]
At least two tests have been observed to generate unrelated failures:
- ``qutip.tests.test_subsys_apply``
- ``qutip.tests.test_fidelity2``
I haven't seen any others recently (at least, not since resolving #425), but if we observe any, we should add them here so that we can be sure everything works for 3.2.0.

**Comment by ajgpitch** [comment]
Good plan

**Comment by ajgpitch** [comment]
Looks like this failed in the current master build
test_sp_eigs.py", line 234, in test_DenseValsOnly
Along with other instances of test_subsys_apply

**Comment by nonhermitian** [comment]
We have not modified the sp_eigs code in some time. Also, the only error that I have ever seen is subsys_apply.  Taking care of that test would cure most, if not all, of our issues.

**Comment by ajgpitch** [comment]
The most recent three PR should resolve all error and warnings in the tests. I will merge them all later today unless there any objections

**Comment by nonhermitian** [comment]
This is fixed.
