### ISSUE TITLE
Link to Bloch_Decay.mp4 in User Guide seems broken

### ISSUE THREAD

**Issue by tilek** [qutip/qutip#800]
There is a Bloch_Decay.mp4 link at the bottom of the [Plotting on the Bloch Sphere](http://qutip.org/docs/4.1/guide/guide-bloch.html#plotting-on-the-bloch-sphere) webpage.

When I click on it I get a 404 error from linked Google Code page:
http://qutip.googlecode.com/svn/doc/figures/bloch_decay.mp4

**Comment by wuisawesome** [comment]
This sounds like more of a documentation issue caused during migration from google code, not really an issue with the framework.

The movie can be found here https://github.com/qutip/qutip-doc/raw/master/figures/bloch_decay.mp4

**Comment by tilek** [comment]
Thanks Alexander!
What is the right channel to report documentation issues?

**Comment by nathanshammah** [comment]
Thank you @wuisawesome for the fix and @tilek for spotting the bug. The correct place to open such issue would have been in [`qutip/qutip-doc`](https://github.com/qutip/qutip-doc). 
Now clicking on the link from Chrome downloads the video. In order to view it online something like [this](https://stackoverflow.com/questions/48820321/how-to-force-a-file-mp4-to-transfer-from-github-to-readthedocs) might be needed but [PR 77](https://github.com/qutip/qutip-doc/pull/77) fixes the bug.
