### ISSUE TITLE
Qobj.overlap is quite slow

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#818]
Hi,

It seems `Qobj.overlap` is slower than calling raw numpy methods on `full` objects when computing a bunch of overlaps with the same vectors. This is typically the case in [my rework of the floquet module](https://github.com/Phyks/qutip/blob/64a4b7d8366751ec04e99bc982c3577009281638/qutip/floquet.py#L607-L615).

Minimal code to reproduce is:

```python
import time

import numpy as np
import qutip

f_a = qutip.coherent(100, 10)
f_b = qutip.coherent(100, 10)

t = time.time()
for i in range(10000):
    f_b.overlap(f_a)
print(time.time() - t)

t = time.time()
f_a = f_a.full()
f_b = f_b.full()
for i in range(10000):
    np.dot(np.conj(f_a.T), f_b)
print(time.time() - t)
```

Which outputs

> 0.8274698257446289
> 0.024214982986450195

(numpy version is 40 times faster)

Is it something expected? Thanks

**Comment by nonhermitian** [comment]
Coherent states are dense, so yes,expected.

**Comment by Phyks** [comment]
Ok. Wouldn't it be possible for qutip to have an efficient `overlap` method when the states are dense as well? Like, fallback to the `numpy` version?

Otherwise, I guess adding a note in the doc about this particular use case, when computing overlaps with dense states might be useful. I did not find anything like this, and it would help make code using qutip more efficient. This could be [here](http://qutip.org/docs/4.0.2/apidoc/classes.html?highlight=overlap#qutip.Qobj.overlap) for instance.

**Comment by ajgpitch** [comment]
For most of the operations, e.g. +, -, *, numpy will be much faster than fast_csr when the matrix is dense. There is probably a good case for having an option to convert to full to make these operators when one knows that the data will be dense. However it would reduce efficiency to check density each time. Will take some thinking about to make it in a tidy way though.

A more general discussion of a dense qobj is in #437

**Comment by nonhermitian** [comment]
The density is actually already computed for you since you know number of nonzeros and shape automatically.

**Comment by jakelishman** [comment]
Closing for same reason as #437.

**Comment by dev-aditya** [comment]
Has this issue been resolved? Because I could see the same problem in the latest version of Qutip too!

**Comment by AGaliciaMartinez** [comment]
Hi @dev-aditya, did you try running the code with QuTiP 5.0.0? It is currently in a pre release which means you need to install it with `pip install --pre qutip`. This new version introduces many changes and since it is a pre release there may be some rough edges still. The main reason you will see a performance improvement for this issue is the new data layer implementation. In a nutshell, it now supports not only sparse arrays, already present in QuTiP 4, but also dense arrays (numpy-like arrays).  Dense arrays are better suited for this operation and hence you should expect an improvement using them. I hope you can give a try to QuTiP 5 and feel free to let us know how it performs :smile:.
