### ISSUE TITLE
Problem with qutip on windows 10

### ISSUE THREAD

**Issue by hchanzy** [qutip/qutip#860]
I installed anaconda on windows 10. 
I used then "pip install qutip", and I get this error : 
File "\lib\distutils\cygwinccompiler.py" line 129, in __init__
       if self.ld_version >= "2.10.90" : 
TypeError: '>=' not supported between instances of 'NoneType' and 'str'

**Comment by hchanzy** [comment]
When I try, I have this problem, what should I do ? 
![image](https://user-images.githubusercontent.com/28700202/39813180-b2e0302e-538f-11e8-97c5-a6cde3781fb1.png)

**Comment by sahmed95** [comment]
Hi, I think it might either be an issue with your conda version or a conflict due to mixing things from the conda-forge and the default conda channel. 

There are two options which you can try:

1. Update all packages and conda by running

```
conda update --all
```
and then trying to reinstall qutip from the default conda repo (and not conda-forge) with

```
conda install qutip
```

2. Add the conda-forge channel as priority with 
```conda config --add channels conda-forge
```
and then update all with
```
conda update --all
```
and finally installing qutip with

```
conda install -c conda-forge qutip
```

The last option would be to uninstall conda, install the latest Miniconda which does not install any package by default and then installing qutip from the conda-forge version with
```
conda install -c conda-forge qutip
```

All three suggestions should just take a couple of minutes. If you could tell me the Anaconda version, it would be very helpful (```conda --version```)

**Comment by hchanzy** [comment]
I updated anaconda, and then I installed it, and I finally managed to install qutip.
My version was 4.4.10
