### ISSUE TITLE
Generate time-dependent Hamiltonian for given quantum circuit

### ISSUE THREAD

**Issue by SachinCompton** [qutip/qutip#946]
Hi,

Sometimes I want to simulate the exact behavior of my quantum circuit, i.e. work out the time-dependent Hamiltonian for a specific gate sequence and Hamiltonian of each gate. Then solve the Lindblad master equation with some collapse operator. Is there an easy way to generate the time-dependent Hamiltonian?

**Comment by sahmed95** [comment]
Dear @Coxious, thanks for opening the issue. At the moment, I can see only a method to return the propagators for a given quantum circuit in [qutip.qip.circuit](https://github.com/qutip/qutip/blob/master/qutip/qip/circuit.py#L892). I am guessing that you would be interested in implementing something there to return the full time dependent Hamiltonian for the circuit and then use mesolve to simulate this Hamiltonian with some collapse operators?

If you have any prototype code, please do share and we can discuss more. @nwlambert  and @ajgpitch  are on board with this too and this seems very relevant.

**Comment by sahmed95** [comment]
I also come across these questions on time-dependent evolutions where the time-dependent part of the Hamiltonian does not look like what QuTiP asks, i.e., A f(t), where A is an operator and f(t) some time-dependent function giving the coefficients. In those cases, I suggest directly moving to a superoperator picture and solving the equation,

dp/dt = L(t) p where L(t) now contains the superoperator representation of the full Hamiltonian.

@nonhermitian could you please comment if the QuTiP TD stuff was made only for Hamiltonians which can be written in this A f(t) form only?

**Comment by nonhermitian** [comment]
It is. But what is the use case where that cannot be done?

**Comment by sahmed95** [comment]
What if for different time slices, A itself changes as A(t)? i.e., one would like to explicitly define the time-dependent part as a function which returns an operator and not just some constant A with the coefficients changing as f(t).

**Comment by nonhermitian** [comment]
Which is equivalent to setting a term to zero after some time, and making a new one nonzero. All can be done with be done by setting the coefficient. However, there is room for improvement in this scenario

**Comment by sahmed95** [comment]
Yes, perhaps there is room for making this easier and more efficient.

I see that in the non-markovian methods like qutip.nonmarkov.heom, this is possible by constructing a superoperator L(t) and then using the standard ODE solver. Do you think we can tweak mesolve somehow to do this?

**Comment by sahmed95** [comment]
Just to add, the `rhs_generate` already seems to be doing this for TD Hamiltonians.

**Comment by ajgpitch** [comment]
There is nothing in the heom ode solve that is not in the mesolve. mesolve can take superop L, that is solve dp/dt = L(t) p, just so long as L(t) = f1(t)L1 + f2(t)L2 ...
I have given some thought to how we can have a more general L(t), in the context of the heom, where for instance we might want to have time-dependent Matsubara terms. These would then occur many times in elements of the L, and so could potentially be solved efficiently. I'll add it to my list of things to discuss with @Ericgig when we meet in a few weeks. The new `QobjEvo` may perhaps have gone some way in this direction already.

**Comment by PZJuly** [comment]
I find the discussion here relevant to a question I asked in QuTip mail
list. (Hope it doesn't interrupt your discussions:p)

My previous question with the title "Possible to realize a decay rate
depending on state occupation?" can be seen here
https://groups.google.com/forum/#!topic/qutip/BqUZQEQN1c4. Paul Nation
kindly gave me some directions there.

He suggested me define a Liouvillian with a Python function and
use rhs_with_state for solving. But unfortunately I didn't figure out how
this should be done. In case you are familiar with this approach, would you
please enlighten me? Thanks a lot!

Best regards, Pu Zhang
--
Faculty at School of Physics, Huazhong University of Science and Technology
Room 819 (N.), Yifu Science and Technology Building
1037 Luoyu Road, Wuhan, China
E-mail: puzhang0702@hust.edu.cn <puzha@fotonik.dtu.dk>
Homepage: www.researchgate.net/profile/Pu_Zhang4
Phone: +86 18871860394

**Comment by ajgpitch** [comment]
@PZJuly I have posted an answer to your question on
https://groups.google.com/forum/#!topic/qutip/BqUZQEQN1c4

I agree the docs http://qutip.org/docs/latest/guide/dynamics/dynamics-time.html do seem to include an example using `rhs_with_state`

**Comment by PZJuly** [comment]
Thank you, Alex, for your kind reply!

Which example do you refer to? I don't see the key word rhs_with_state on
the page (http://qutip.org/docs/latest/guide/dynamics/dynamics-time.html).
Did I misunderstand you?

Best regards, Pu Zhang
--
Faculty at School of Physics, Huazhong University of Science and Technology
Room 819 (N.), Yifu Science and Technology Building
1037 Luoyu Road, Wuhan, China
E-mail: puzhang0702@hust.edu.cn <puzha@fotonik.dtu.dk>
Homepage: www.researchgate.net/profile/Pu_Zhang4
Phone: +86 18871860394

**Comment by ajgpitch** [comment]
@PZJuly sorry, I missed the vital word *not* from my comment above. I have updated it now.
Hopefully my reply on the Google group will be sufficient to help you for now.

**Comment by PZJuly** [comment]
Dear all,

I'm trying to install the latest release of QuTip on Ubuntu system. Since
our workstation hasn't been connected to internet, I
downloaded Anaconda3-2019.03-Linux-x86_64 and qutip-4.3.1.tar, and attempt
to install from source code.

Firstly I successfully installed Anaconda with the command:
bash ~/Downloads/Anaconda3-2019.03-Linux-x86_64.sh

Then in the conda environment I typed the command:
python setup.py install

I get the following error message:

gcc -pthread -B /home/pz/anaconda3/compiler_compat -Wl,--sysroot=/
-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iqutip/cy
-I/home/pz/anaconda3/lib/python3.7/site-packages/numpy/core/include
-I/home/pz/anaconda3/lib/python3.7/site-packages/numpy/core/include
-I/home/pz/anaconda3/include/python3.7m -c qutip/cy/spmatfuncs.cpp -o
build/temp.linux-x86_64-3.7/qutip/cy/spmatfuncs.o -w -O3 -march=native
-funroll-loops
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1

It seems the gcc compiler isn't correctly located? Or what else problem.

I checked the gcc version on the workstation:
gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1~18.10) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

whereis gcc
gcc: /usr/bin/gcc /usr/lib/gcc /usr/share/man/man1/gcc.1.gz

How can I direct the installer to find the gcc compiler?

Thanks!
Best regards, Pu Zhang
--
Faculty at School of Physics, Huazhong University of Science and Technology
Room 819 (N.), Yifu Science and Technology Building
1037 Luoyu Road, Wuhan, China
E-mail: puzhang0702@hust.edu.cn <puzha@fotonik.dtu.dk>
Homepage: www.researchgate.net/profile/Pu_Zhang4
Phone: +86 18871860394

**Comment by ajgpitch** [comment]
Hi,
I had a similar issue recently. See
https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory

The second suggestion

sudo apt-get update
sudo apt-get install --reinstall build-essential

worked for me.

Best of luck with it.

Alex

**Comment by nathanshammah** [comment]
This looks like it is handled by the new `noise` module of #1065.
