### ISSUE TITLE
Integer overflow on windows

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#968]
The following error occurred several times while running the tests on my machine:
```
======================================================================
ERROR: Stochastic: ssesolve: heterodyne, time-dependent H
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Boxi\Miniconda3\envs\qutip-dev-py3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\tests\test_stochastic_se.py", line 208, in test_ssesolve_heterodyne
    map_func=parallel_map, args={"a":2})
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\stochastic.py", line 698, in ssesolve
    args=args, **kwargs)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\stochastic.py", line 417, in __init__
    self.noise = np.random.randint(0, 2**32, ntraj).astype("u4")
  File "mtrand.pyx", line 990, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32

----------------------------------------------------------------------
```
It is due to the fact that the default integer of python on windows is int32 instead of int64. `np.random.randint(0, 2**32)` produces the same error on my machine. Maybe it is better to add `dtype=np.int64` or `dtype=np.uint32` since they are platform independent. If you agree I can work on fixing it.

**Comment by nathanshammah** [comment]
Thank you for finding the source to this testing error and proposing a fix. It would be best to have @Ericgig's opinion on this, as he refurbished the stochastic solvers and has been working on migration from int32 to int64, see also project [4](https://github.com/qutip/qutip/wiki//Google-Summer-of-Code-2019#4-abstraction-of-the-quantum-object-class-qutipqobjqobj) in Google Summer of Code.

**Comment by nonhermitian** [comment]
It needs to be 2^32-1

**Comment by nonhermitian** [comment]
Or better yer np.iinfo(np.int32).max

**Comment by Ericgig** [comment]
Thank you for finding it. You can make a patch if you have time. nonhermitian's `np.iinfo(np.int32).max` seems the best solution. seeds should be `dtype=np.uint32`

**Comment by ajgpitch** [comment]
@BoxiLi nice work, thanks

**Comment by egdeist** [comment]
Hello,
I am having the same ValueError on Windows that @BoxiLi  describes in the beginning of this thread. 
I see that this was fixed by changing the line 
noise = np.random.randint(0, 2**32, ntraj)
to 
noise = np.random.randint(0, np.iinfo(np.uint32).max, ntraj, dtype=np.uint32).
I have two questions. 
1) I just installed qutip using the installation instructions (conda install qutip). Do I expect the change described above to be present in the version that I installed (4.5.0)? Because I still have the original line with 2**32. Please let me know if there is something else I can do to get a more up-to-date version. 
2) BoxiLi's correction actually still doesn't work for me. np.iinfo(np.uint32).max gives 2**32-1; what I need to not get the ValueError is 2**31. 
I am wondering if I should just go ahead and make this change in my local copy of stochastic.py to get the code to run, or if the simulations will be incorrect if I change the range of the random numbers in this way? Sorry if this is a dumb question. 
Thanks for your help.
Emma

**Comment by BoxiLi** [comment]
Hi @egdeist, thanks for finding it, again. Somehow my change was reverted by #990. And no one realised it since QuTiP isn't automatically tested on windows. 

Do you still have after changing it to `np.random.randint(0, np.iinfo(np.uint32).max, ntraj, dtype=np.uint32)`?
https://github.com/qutip/qutip/blob/8dbbe77f1c22ded7dc9c445d0dd82a3120fea94f/qutip/stochastic.py#L380-L390
https://github.com/qutip/qutip/blob/8dbbe77f1c22ded7dc9c445d0dd82a3120fea94f/qutip/stochastic.py#L410-L420

**Comment by egdeist** [comment]
Thanks @BoxiLi. 
Yes, I realize now that it does work if I change it to `np.random.randint(0, np.iinfo(np.uint32).max, ntraj, dtype=np.uint32)`?
One more small q-- in the above, line 385 uses np.iinfo(np.unit32).max, but line 417 uses np.iinfo(np.int32).max -- does it matter what is used / is this a deliberate difference?

**Comment by Ericgig** [comment]
numpy seeds must be 32bit usingned int. Thus `np.uint32` is better, `np.int32` will cut half the available seeds. #1219 will fix this but it will take some time before it is officially released.
