### ISSUE TITLE
Unitary operator acting on density matrix

### ISSUE THREAD

**Issue by artix41** [qutip/qutip#977]
Given a density matrix `rho` created in QuTiP, I'd like to apply a unitary operator to it, like in the following code:

```python
rho_coherent = coherent_dm(10, 0)
rho_squeezing = squeeze(10,0.25)(rho_coherent)
```

However, it raises the following error:
```batch
TypeError("Can only act oper on ket or oper.")
```

I've fixed it temporarily by adding another `if` line 775 of `qobj.py`:

```python
elif self.type == "oper":
    if other.type == "ket":
        return self * other
    elif other.type == "oper":
        return self * other * self.dag()
    else:
        raise TypeError("Can only act oper on ket or oper.")
```

However, it's only a hack because it works only when the main object is a hermitian operator (observable or density matrix) and other is a unitary matrix. 

What do you think would be a good solution to solve this issue?

**Comment by quantshah** [comment]
Thank you @artix41 for opening this discussion.  But I think the current behavior protects the user from making the mistake of applying an operator to a density matrix thinking of it as a ket. So this should not work:
```
rho_coherent = coherent_dm(10, 0)
squeeze(10,0.25) rho_coherent
```
as you are making a mistake and instead should have explicitly done `squeeze(10,0.25)*rho_coherent*squeeze(10,0.25).dag()`

But I can understand how this might be a nice feature where QuTiP can automatically do it. I am not sure though if this need to be implemented as a separate feature since the proper way to do it is just a one liner.

@nathanshammah @ajgpitch Any comments?

**Comment by nathanshammah** [comment]
I agree.
